### ISSUE TITLE
Error when building protobuf: js_embed: not found

### ISSUE THREAD

**Issue by ventusff** [sh1r0/caffe-android-lib#100]
I've got an error when building protobuf:

[ 40%] Generating /home/ventus/caffe-android-lib/protobuf/src/google/protobuf/compiler/js/well_known_types_embed.cc
/bin/sh: 1: js_embed: not found
CMakeFiles/libprotoc.dir/build.make:61: recipe for target '/home/ventus/caffe-android-lib/protobuf/src/google/protobuf/compiler/js/well_known_types_embed.cc' failed

**Comment by sh1r0** [comment]
Hi @ventusff, please provide more information about your build environment, such as OS, cmake version, NDK version, etc. Thanks.

**Comment by ventusff** [comment]
Hi @sh1r0 , well first thank you for noticing my questions, and I'm happy to tell you that all my problems were just solved...The biggest problem was that I didn't download this whole thing via "git clone --recursive ..." way , BUT  via "Download Zip" way , and I  downloaded each package one by one using "Download Zip". And this cause a serious problem that what I had downloaded is quite different from what you put out here, and of course I will meet a lot of problems while I run the "./build.sh"...and later when I managed to clone these via "git clone --recursive..."way , immediately there's no error at all while running the ./build.sh. Everything was just solved, I received a "DONE!!" in the end in the terminal. And still , thank you so much:) This package helps me a lot in our programs

**Comment by ventusff** [comment]
And also , just after the successfully build, I find the "xxx.so" files in the folders. So the former issue
[  https://github.com/sh1r0/caffe-android-demo/issues/56  ] was just solved too:)

**Comment by ventusff** [comment]
@sh1r0 You can close this now:) Thank you~

**Comment by sh1r0** [comment]
Good to hear that, thanks.
