### ISSUE TITLE
Can't find makefile and another problem

### ISSUE THREAD

**Issue by DragonBornHD** [sh1r0/caffe-android-lib#104]
There are two problem when I run the build.sh, would you help me please?

The first one, I have already install openblas and opencv, could I ignore the build_openblas.sh and build_opencv.sh ? 

The second one, the error that can't find makefile occur when I run the build.sh or build_boost.sh , I don't know where to find the makefile. This problem also occur when I run the build_openblas.sh. 
My ndk version is r10d. 

Thank you very much. Sorry for my poor english.

**Comment by sh1r0** [comment]
Please follow the build steps [here](https://github.com/sh1r0/caffe-android-lib#build), and note that using `build.sh` to build all dependencies would be a better choice to avoid  any possible conflict. Thanks.

**Comment by sh1r0** [comment]
I'm gonna closing this as docker support is added.
