### ISSUE TITLE
cannot stat 'libopenblas_armv8-r0.2.18.a': No such file or directory

### ISSUE THREAD

**Issue by smileForCode** [sh1r0/caffe-android-lib#105]
i compile this library on ubuntu 16.04 ,then i get these errors:
"install: cannot stat 'libopenblas_armv8-r0.2.18.a': No such file or directory
Makefile.install:23: recipe for target 'install' failed
make[1]: *** [install] Error 1
make[1]: Leaving directory '/home/dev/Documents/cafferFinder/caffe-android-lib/OpenBLAS'
Makefile:313: recipe for target 'install' failed
make: *** [install] Error 2
Failed to build OpenBLAS"

**Comment by huxdhxa** [comment]
on ubuntu 14.04(64bit),found the same error

**Comment by sh1r0** [comment]
Please refer to https://github.com/sh1r0/caffe-android-lib/issues/65, what is the version of cmake of you guys?

**Comment by huxdhxa** [comment]
I use a fresh Ubuntu 14.04 vmware.And removed the old cmake 2.8, install a new cmake 3.3.2.

**Comment by sh1r0** [comment]
Following the steps [here](https://github.com/sh1r0/caffe-android-lib#build), is there still an issue?

**Comment by huxdhxa** [comment]
My Android ndk is r13b,i will change to Android NDK r11c and try again.thanks for your reply very much!

**Comment by mmiirroo** [comment]
@sh1r0 I rebuild docker image twice，and ./build.sh
also the same problem

> make[1]:
 Leaving directory '/caffe-android-lib/OpenBLAS/kernel'
make -j 1 -f Makefile.install install
make[1]: Entering directory '/caffe-android-lib/OpenBLAS'
Generating openblas_config.h in /caffe-android-lib/android_lib/openblas/include
Generating f77blas.h in /caffe-android-lib/android_lib/openblas/include
Generating cblas.h in /caffe-android-lib/android_lib/openblas/include
Copying the static library to /caffe-android-lib/android_lib/openblas/lib
install: cannot stat 'libopenblas_atom-r0.2.18.a': No such file or directory
Makefile.install:23: recipe for target 'install' failed
make[1]: *** [install] Error 1
make[1]: Leaving directory '/caffe-android-lib/OpenBLAS'
Makefile:313: recipe for target 'install' failed
make: *** [install] Error 2
Failed to build OpenBLAS

**Comment by Bshowg** [comment]
@sh1r0  same problem for me too 

```
make[1]: Leaving directory '/caffe-android-lib/OpenBLAS/kernel'
make -j 1 -f Makefile.install install
make[1]: Entering directory '/caffe-android-lib/OpenBLAS'
Generating openblas_config.h in /caffe-android-lib/android_lib/openblas/include
Generating f77blas.h in /caffe-android-lib/android_lib/openblas/include
Generating cblas.h in /caffe-android-lib/android_lib/openblas/include
Copying the static library to /caffe-android-lib/android_lib/openblas/lib
Makefile.install:23: recipe for target 'install' failed
make[1]: Leaving directory '/caffe-android-lib/OpenBLAS'
Makefile:313: recipe for target 'install' failed
Failed to build OpenBLAS
install: cannot stat 'libopenblas_atom-r0.2.18.a': No such file or directory
make[1]: *** [install] Error 1
make: *** [install] Error 2
```
