### ISSUE TITLE
Failed to build OpenBLAS

### ISSUE THREAD

**Issue by husteleven** [sh1r0/caffe-android-lib#107]
excuse me
when I build the caffe-android-lib,I get the below error, this error same to the #72 and #77. I have changed the version of ndk, but the result is the same。I have no idea what to do, please help me.
environment：Ubuntu 14.04 android-ndk-r13b .. cmake version 3.3.2

C Compiler (/home/bing/android-ndk-r13b/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86/bin/aarch64-linux-android-gcc --sysroot=/home/bing/android-ndk-r13b/platforms/android-21/arch-arm64) is something wrong.
1 at ./c_check line 24.
make: *** [config.h] Error 2
Makefile.system:165: Makefile.conf: No such file or directory
Makefile.system:906: Makefile.: No such file or directory
make: *** No rule to make target `Makefile.'.  Stop.
Failed to build OpenBLAS

**Comment by sh1r0** [comment]
Hi @husteleven, I have succeeded in building all the libs with cmake 3.5.2, and android ndk of version r13b  and r14b respectively, FYI. Please check the build steps [here](https://github.com/sh1r0/caffe-android-lib#build).

**Comment by sh1r0** [comment]
Please refer to the latest commit (b9b0ba7), I just added docker support for building this project.
