### ISSUE TITLE
error: uses VFP register arguments, output does not

### ISSUE THREAD

**Issue by hgffly** [sh1r0/caffe-android-lib#108]
I have built OpenBLAS libraries successfully. But when I put the libraries in my Android project and try to build it, an error is raised:

Error:error: ../../../../src/main/jniLibs/armeabi-v7a/libopenblas.a(cblas_sasum.o) uses VFP register arguments, output does not
Error:error: ../../../../src/main/jniLibs/armeabi-v7a/libopenblas.a(openblas_env.o) uses VFP register arguments, output does not
Error:error: ../../../../src/main/jniLibs/armeabi-v7a/libopenblas.a(dscal_k.o) uses VFP register arguments, output does not
/data/Android/Sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/arm-linux-androideabi/bin/ld
Error:error: ../../../../src/main/jniLibs/armeabi-v7a/libopenblas.a(cblas_saxpy.o) uses VFP register arguments, output does not
Error:error: ../../../../src/main/jniLibs/armeabi-v7a/libopenblas.a(cblas_scopy.o) uses VFP register arguments, output does not
Error:error: ../../../../src/main/jniLibs/armeabi-v7a/libopenblas.a(cblas_sdot.o) uses VFP register arguments, output does not
Error:error: ../../../../src/main/jniLibs/armeabi-v7a/libopenblas.a(cblas_sscal.o) uses VFP register arguments, output does not

What's the matter with it?
How could I resolve it? thanks

**Comment by sh1r0** [comment]
How did you build openblas?

**Comment by hgffly** [comment]
I built the openblas in the way you mention in the page, with export ANDROID_ABI=`armeabi-v7a-hard-softfp with NEON`. But I just found the libraries of OpenBLAS is built with some errors, the error messages are as below :

getarch_2nd.c: In function ‘main’:
getarch_2nd.c:12:35: error: ‘SGEMM_DEFAULT_UNROLL_M’ undeclared (first use in this function)
     printf("SGEMM_UNROLL_M=%d\n", SGEMM_DEFAULT_UNROLL_M);
                                   ^
getarch_2nd.c:12:35: note: each undeclared identifier is reported only once for each function it appears in
getarch_2nd.c:13:35: error: ‘SGEMM_DEFAULT_UNROLL_N’ undeclared (first use in this function)
     printf("SGEMM_UNROLL_N=%d\n", SGEMM_DEFAULT_UNROLL_N);
                                   ^
getarch_2nd.c:14:35: error: ‘DGEMM_DEFAULT_UNROLL_M’ undeclared (first use in this function)
     printf("DGEMM_UNROLL_M=%d\n", DGEMM_DEFAULT_UNROLL_M);
                                   ^
getarch_2nd.c:15:35: error: ‘DGEMM_DEFAULT_UNROLL_N’ undeclared (first use in this function)
     printf("DGEMM_UNROLL_N=%d\n", DGEMM_DEFAULT_UNROLL_N);
                                   ^
getarch_2nd.c:19:35: error: ‘CGEMM_DEFAULT_UNROLL_M’ undeclared (first use in this function)
     printf("CGEMM_UNROLL_M=%d\n", CGEMM_DEFAULT_UNROLL_M);
                                   ^
getarch_2nd.c:20:35: error: ‘CGEMM_DEFAULT_UNROLL_N’ undeclared (first use in this function)
     printf("CGEMM_UNROLL_N=%d\n", CGEMM_DEFAULT_UNROLL_N);
                                   ^
getarch_2nd.c:21:35: error: ‘ZGEMM_DEFAULT_UNROLL_M’ undeclared (first use in this function)
     printf("ZGEMM_UNROLL_M=%d\n", ZGEMM_DEFAULT_UNROLL_M);
                                   ^
getarch_2nd.c:22:35: error: ‘ZGEMM_DEFAULT_UNROLL_N’ undeclared (first use in this function)
     printf("ZGEMM_UNROLL_N=%d\n", ZGEMM_DEFAULT_UNROLL_N);
                                   ^
getarch_2nd.c:69:50: error: ‘SGEMM_DEFAULT_Q’ undeclared (first use in this function)
     printf("#define SLOCAL_BUFFER_SIZE\t%ld\n", (SGEMM_DEFAULT_Q * SGEMM_DEFAULT_UNROLL_N * 4 * 1 *  sizeof(float)));
                                                  ^
getarch_2nd.c:70:50: error: ‘DGEMM_DEFAULT_Q’ undeclared (first use in this function)
     printf("#define DLOCAL_BUFFER_SIZE\t%ld\n", (DGEMM_DEFAULT_Q * DGEMM_DEFAULT_UNROLL_N * 2 * 1 *  sizeof(double)));
                                                  ^
getarch_2nd.c:71:50: error: ‘CGEMM_DEFAULT_Q’ undeclared (first use in this function)
     printf("#define CLOCAL_BUFFER_SIZE\t%ld\n", (CGEMM_DEFAULT_Q * CGEMM_DEFAULT_UNROLL_N * 4 * 2 *  sizeof(float)));
                                                  ^
getarch_2nd.c:72:50: error: ‘ZGEMM_DEFAULT_Q’ undeclared (first use in this function)
     printf("#define ZLOCAL_BUFFER_SIZE\t%ld\n", (ZGEMM_DEFAULT_Q * ZGEMM_DEFAULT_UNROLL_N * 2 * 2 *  sizeof(double)));
                                                  ^
make: *** [getarch_2nd] Error 1

My OS is Ubuntu16.04, NDK is android-ndk-r11c, cmake version 3.5.1
The README.md says you Tested with Android NDK r11c and cmake 3.3.2 on Ubuntu 14.04
Do I need to have identical settings as yours?
If not , how can I resolve the errors ? Thanks very much
