### ISSUE TITLE
How to make pycaffe and build _caffe module

### ISSUE THREAD

**Issue by DevilGragon** [sh1r0/caffe-android-lib#117]
I want to deploy caffemodel by python. But after i modified build_caffe.sh with "-DBUILD_python=ON \", it reported an error "The dependency target "pycaffe" of target "pytest" does not exist." 
    I tried to delete pytest option and configuring failed.
    Could anyone help me?

**Comment by sh1r0** [comment]
Hi @DevilGragon, currently, there is no plan to support pycaffe, as that'll need to get libpython on compilation time and handle some issues for runtime which makes things more complicated.
