### ISSUE TITLE
Failed to build OpenBLAS

### ISSUE THREAD

**Issue by lesolar** [sh1r0/caffe-android-lib#118]
make[1]: Leaving directory `/home/lesolar/Software/caffe3/OpenBLAS/kernel'
touch libopenblas_armv8p-r0.3.0.dev.a
make -j 8 -C test all
make[1]: Entering directory `/home/lesolar/Software/caffe3/OpenBLAS/test'
/home/lesolar/Software/android-ndk-r11c/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/bin/aarch64-linux-android-gfortran --sysroot=/home/lesolar/Software/android-ndk-r11c/platforms/android-21/arch-arm64 -O2 -Wall -fopenmp -fPIC -march=armv8-a -c sblat1.f  -o sblat1.o
make[1]: /home/lesolar/Software/android-ndk-r11c/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/bin/aarch64-linux-android-gfortran: Command not found
make[1]: *** [sblat1.o] Error 127
make[1]: Leaving directory `/home/lesolar/Software/caffe3/OpenBLAS/test'
make: *** [tests] Error 2
Failed to build OpenBLAS

make failed OpenBlas

**Comment by BenwenZhang** [comment]
I changed the build_openblas.sh inside scripts folder as follow

make clean
make -j${N_JOBS} \
     CC="${CROSS_SUFFIX}gcc --sysroot=$SYSROOT" \
     FC="${CROSS_SUFFIX}gfortran --sysroot=$SYSROOT" \
     CROSS_SUFFIX=$CROSS_SUFFIX \
     HOSTCC=gcc USE_THREAD=1 NUM_THREADS=1 USE_OPENMP=0 \
     NO_LAPACK=$NO_LAPACK TARGET=$TARGET BINARY=$BINARY

In this case, OpenBLAS can be successfully compiled. But I am still not sure whether the "USE_OPENMP" option affect the efficiency of caffe running on Android.

**Comment by sh1r0** [comment]
Please refer to the latest commit (b9b0ba7), I just added docker support for building this project.
