### ISSUE TITLE
hi， Failed to build OpenBLAS,libopenblas_atom-r0.2.18.a

### ISSUE THREAD

**Issue by dasshr** [sh1r0/caffe-android-lib#119]
ubuntu version ,cmake version, ndk version, every way you tell
i had all tried
still the issue:
make -j 1 -f Makefile.install install
make[1]: Entering directory '/home/dasshr/caffe-android-lib/OpenBLAS'
Generating openblas_config.h in /home/dasshr/caffe-android-lib/android_lib/openblas/include
Generating f77blas.h in /home/dasshr/caffe-android-lib/android_lib/openblas/include
Generating cblas.h in /home/dasshr/caffe-android-lib/android_lib/openblas/include
Copying LAPACKE header files to /home/dasshr/caffe-android-lib/android_lib/openblas/include
Copying the static library to /home/dasshr/caffe-android-lib/android_lib/openblas/lib
install: cannot stat 'libopenblas_atom-r0.2.18.a': No such file or directory
Makefile.install:23: recipe for target 'install' failed
make[1]: *** [install] Error 1
make[1]: Leaving directory '/home/dasshr/caffe-android-lib/OpenBLAS'
Makefile:313: recipe for target 'install' failed
make: *** [install] Error 2
Failed to build OpenBLAS

i hope you can have a look....i m new here 0.0
thank you!

**Comment by sh1r0** [comment]
Please refer to the latest commit (b9b0ba7), I just added docker support for building this project.
