### ISSUE TITLE
Failed to build OpenBLAS: cannot stat 'libopenblas_armv8p-r0.3.0.dev.so': No such file or directory

### ISSUE THREAD

**Issue by wakeee** [sh1r0/caffe-android-lib#120]
I clone the lasted code from git and build failed. 

**install: cannot stat 'libopenblas_armv8p-r0.3.0.dev.so': No such file or directory**

There is not a "libopenblas_armv8p-r0.3.0.dev.so" but a "libopenblas_armv8p-r0.3.0.dev.a" in android_lib/openblas/lib

make[1]: Leaving directory '/cloud/share/caffe-android-lib/OpenBLAS/kernel'
make -j 8 -f Makefile.install install
make[1]: Entering directory '/cloud/share/caffe-android-lib/OpenBLAS'
Generating openblas_config.h in /cloud/share/caffe-android-lib/android_lib/openblas/include
Generating f77blas.h in /cloud/share/caffe-android-lib/android_lib/openblas/include
Generating cblas.h in /cloud/share/caffe-android-lib/android_lib/openblas/include
Copying LAPACKE header files to /cloud/share/caffe-android-lib/android_lib/openblas/include
Copying the static library to /cloud/share/caffe-android-lib/android_lib/openblas/lib
Copying the shared library to /cloud/share/caffe-android-lib/android_lib/openblas/lib
install: cannot stat 'libopenblas_armv8p-r0.3.0.dev.so': No such file or directory
Makefile.install:24: recipe for target 'install' failed
make[1]: *** [install] Error 1
make[1]: Leaving directory '/cloud/share/caffe-android-lib/OpenBLAS'
Makefile:323: recipe for target 'install' failed
make: *** [install] Error 2
Failed to build OpenBLAS

**Comment by sh1r0** [comment]
Please check your environment or try to use [docker](https://github.com/sh1r0/caffe-android-lib#recommended-using-docker) for simplicity.

**Comment by wakeee** [comment]
My environment:
Ubuntu 16.04.1 LTS
Cmake version  3.5.1
android-ndk-r15c

**Comment by sh1r0** [comment]
Probably caused by incompatible ndk version, please try to get an older version of ndk, or simply use docker instead. Thanks.
