### ISSUE TITLE
can not use asset manager

### ISSUE THREAD

**Issue by wakeee** [sh1r0/caffe-android-lib#121]
I modified the caffe_jni.cpp file in order to use asset manager to read model file.
Here is my code
```c++
#include <jni.h>
#include <android/asset_manager.h>
#include <android/asset_manager_jni.h>
#include <android/log.h>
...
AAssetManager *mgr = AAssetManager_fromJava(env, assetManager);
AAsset* asset = AAssetManager_open(mgr, filename, AASSET_MODE_BUFFER);
...
```

but I get error when: 
```
[100%] Linking CXX shared library ../lib/libcaffe_jni.so


caffe_jni.cpp:(.text.Java_com_***_loadModel+0x4c): undefined reference to `AAssetManager_fromJava'
caffe_jni.cpp:(.text.Java_com_***_loadModel+0x5c): undefined reference to `AAssetManager_open'
```

I can use '`__android_log_print`' in log.h, but not '`AAssetManager_fromJava`' in asset_manager.h.
why?

**Comment by sh1r0** [comment]
Hi @wakeee, 

You might need to link `caffe_jni` to `libandroid` explicitly. That is, in https://github.com/sh1r0/caffe/blob/080c2381625f1e2c1bbabd7ab4cc8d8581e3d19e/android/CMakeLists.txt#L6, you need to add `libandroid` in `target_link_libraries`.

Before:
```cmake
target_link_libraries(caffe_jni ${Caffe_LINK})
```

After:
```cmake
target_link_libraries(caffe_jni ${Caffe_LINK} android)
```
