### ISSUE TITLE
armeabi-v7a       with: command not found

### ISSUE THREAD

**Issue by Henry-Faull** [sh1r0/caffe-android-lib#126]
Hi, I'm trying to build with docker for armeabi-v7a. All other ABIs have worked fine but because of the with NEON command in the config.sh file:

        ANDROID_ABI=armeabi-v7a-hard-softfp with NEON

I am getting this error:

        ./config.sh: line 44: with: command not found

I am very new to all this. I seem to be missing 'with' but I am not sure what that means or how to solve it?

**Comment by sh1r0** [comment]
Hi @Henry-Faull, thanks for your report.
