### ISSUE TITLE
Feature extraction

### ISSUE THREAD

**Issue by FreakTheMighty** [sh1r0/caffe-android-lib#13]
Thanks for the library. Is it possible extract features from different layers in the network?

**Comment by mtngld** [comment]
Hi,

Try something like that:

```C
  //Feature extraction
    const shared_ptr<Blob<float> >& features = caffe_net->blob_by_name("fc7");
    LOG(INFO) << "Features size " << features->count();
    vector myfeatures  = vector<float>(features->cpu_data(),features->cpu_data()+features->count());
```

Change "fc7" to whatever layer you want

**Comment by isikdogan** [comment]
I'm also trying to extract features. I need the features before they are passed through the softmax layer, just like in the code snippet above. Where should I add this code? Is it caffe_mobile.cpp?
Thanks

**Comment by mtngld** [comment]
Yes, you can simply add it to predict_top_k function or create a dedicated feature extraction function

**Comment by vimalthilak** [comment]
You can always modify the prototxt to extract features that are of interest to you. I have been able to extract features from the output of average pooling layer of a GoogLeNet model by simply removing the last three layers from the deploy prototxt file of the same model. You just re-run Forward() as before.

**Comment by isikdogan** [comment]
Thanks for your responses. I wasn't familiar with the Java Native Interface. I was able to run it by modifying caffe_jni.cpp and caffe_mobile.cpp files.

**Comment by Keyurpatel93** [comment]
isikdogan, can you please share how you modified the caffe_jni.cpp and caffe_mobile.cpp files to be able to extract features from a layer in the network?

**Comment by isikdogan** [comment]
Keyurpatel93, I just noticed your message. I no longer work on that project. The development version of OpenCV seems to have caffe-compatible functions. I don't know if those functions are available in the Android version yet, but if so then it could be more convenient to use them:
http://docs.opencv.org/master/d6/d0f/group__dnn.html

**Comment by sh1r0** [comment]
Thanks to the discussions above. Feature extraction is integrated in the latest master branch, so I'm gonna close this issue.
