### ISSUE TITLE
Is there anyway to compile codes in caffe tools folder so i can do training?

### ISSUE THREAD

**Issue by ZhengRui** [sh1r0/caffe-android-lib#14]
hello today i tried to add this into my Android.mk file so that i can compile caffe.cpp file, because i want to be able to train a network
``` 
$(CLEAR_VARS)

OpenCV_INSTALL_MODULES := on
OPENCV_CAMERA_MODULES := off
OPENCV_LIB_TYPE := STATIC
include $(REMOTE_PATH)/../../opencv/jni/OpenCV.mk

LOCAL_MODULE := caffe_tools

PRORO_CC := caffe/src/caffe/proto/caffe.pb.cc

LOCAL_SRC_FILES := $(PRORO_CC) caffe/tools/caffe.cpp

LOCAL_C_INCLUDES := $(REMOTE_PATH)/../../eigen3 \
    $(LOCAL_PATH)/caffe/include $(LOCAL_PATH)/caffe/include/caffe/proto \
    $(REMOTE_PATH)/../../Boost-for-Android/build/include/boost-1_55 \
    $(REMOTE_PATH)/../../opencv/jni/include \
    $(REMOTE_PATH)/../../../gflags/build/include

LOCAL_STATIC_LIBRARIES += gflags
LOCAL_SHARED_LIBRARIES := caffe
LOCAL_CPPFLAGS += -pthread -fPIC -fexceptions -frtti -std=c++11 -DUSE_EIGEN -DCPU_ONLY
LOCAL_LDLIBS += -lm -llog -L$(REMOTE_PATH)/../../../gflags/build/lib/
LOCAL_ARM_MODE := arm
ifeq ($(TARGET_ARCH_ABI), armeabi-v7a)
LOCAL_ARM_NEON := true
endif

include $(BUILD_SHARED_LIBRARY)
```

i don't know if this is the right direction to make it able to train a network, i compiled gflags by myself and tried to link to it, but i got this error:

```
Error:error: undefined reference to 'google::FlagRegisterer::FlagRegisterer(char const*, char const*, char const*, char const*, void*, void*)'
```

for the 4 functions in caffe.cpp file, i think it's because the gflags is not build with Android platform, but i don't know what should i do now, any guide towards making it able to train a network?

**Comment by sh1r0** [comment]
Sorry for my late response. Did you try to build glags for Android? But actually, it's not required to make it. You can simply copy and modify `train()` in ` caffe/tools/caffe.cpp` and put it somewhere (e.g., caffe_mobile.cpp) and implement a corresponding jni call for the usage.

**Comment by ZhengRui** [comment]
I just include the header files of gflag but i didn't use its compiled library, i noticed that it's not required. After compiling most dependencies for arm platform including leveldb, lmdb, snappy, now i can train mnist dataset and the trained model did get 98% accuracy after i loaded and tested on my laptop. But only leveldb worked well, lmdb got some problems. Also i think start_logger() function may need to be changed a bit to print the training output from caffe correctly. I have putted it down for many days, hope could make it work more smoothly when i got time.

**Comment by sh1r0** [comment]
Sorry for my possible misunderstanding. Your laptop? (ARM-based?)

**Comment by ZhengRui** [comment]
i mean i trained it on the phone, but during training from the output of my android studio it's quite messy, i am not sure how good the model trained, so i loaded to my laptop and test it, accuracy is fine.

**Comment by sh1r0** [comment]
Wow, that's great!!

**Comment by sh1r0** [comment]
Cmake is used to build the caffe lib now (except some modules. e.g. python, matlab, etc.).
