### ISSUE TITLE
Embedding model files into apk

### ISSUE THREAD

**Issue by isikdogan** [sh1r0/caffe-android-lib#15]
Is there a way to embed the prototxt and caffemodel files into the apk file? The loadModel function seems to require a full path to the files, so adding files to the assets folder didn't work.
Thanks

**Comment by sh1r0** [comment]
If you want to pack models and prototxts into the apk using assets, you could refer to [this](http://stackoverflow.com/questions/8474821/how-to-get-the-android-path-string-to-a-file-on-assets-folder).

**Comment by isikdogan** [comment]
Thanks! I was able to pack everything into a small apk file.
