### ISSUE TITLE
Different abis support

### ISSUE THREAD

**Issue by danields761** [sh1r0/caffe-android-lib#16]
Hello.

Are you planing to support not only **armeabi-v7a**? I had tried to do that, i had replaced **APP_ABI** in **Application.mk** to **armeabi**, but had got this error:
`Android NDK: ERROR:caffe-android-lib/caffe-mobile/jni/Android.mk:protobuf: LOCAL_SRC_FILES points to a missing file    
Android NDK: Check that caffe-android-lib/caffe-mobile/jni/../../protobuf/obj/local/armeabi/libprotobuf.a exists  or that its path is correct`

This happened because protobuf library is building only for **armeabi-v7a**, and i can't make it to build for another eabi.

Thanks in advance. 

P.S. sorry for my bad English

**Comment by sh1r0** [comment]
I did not have a try before, but you can try to build protobuf for armeabi. (Are you trying to run caffe on older devices?)

**Comment by liyuming1978** [comment]
run caffe on older devices is crazy...
