### ISSUE TITLE
Redistribution and Licensing

### ISSUE THREAD

**Issue by jbeorse** [sh1r0/caffe-android-lib#2]
I work on Open Data Kit at the University of Washington. Here's a link to our [homepage](https://opendatakit.org/) and to [source code](https://code.google.com/p/opendatakit/) for most of our projects. 

We are interested in using your library in our ODK Scan project. Here's a link to the [source](https://code.google.com/p/opendatakit/source/browse/?repo=scan), but be aware that this is not yet in beta. In short, ODK Scan improves data collection in the field by letting users parse paper forms with an Android device. You take a picture of the form and ODK Scan extracts responses from bubbles, number boxes, etc. It also integrates with our other ODK tools that make it easy to collect, visualize, and sync your data with the cloud.  

We have written an improved number classifier that depends on the Caffe library and had great results with training and classification in a desktop environment. Now that we are transitioning classification to the Android device, we are hoping to build from the work you've done here.

If we credit you and link to this source, are you open to us packaging your code, with our modifications, in our APK? Do you use a particular license, like the one Caffe is using: https://github.com/BVLC/caffe/blob/master/LICENSE ? If we make modifications, would you like us to work together to possibly contribute back here?

Please let me know if you have any questions about us or how we would be using your code. Also, I've got some questions about what Caffe functionality has been ported, what isn't supported, and what kind of work would need to be done to add some of the unsupported features. I'd love to have a conversation about this. 

Jeff Beorse
jbeorse@cs.washington.edu

**Comment by sh1r0** [comment]
Good, I just added a [FreeBSD license](https://github.com/sh1r0/caffe-android-lib/blob/master/LICENSE) like Caffe, and you still need to follow the license for the Caffe core part. It'll be great if you are willing to co-work on and contribute to this repo.

Regarding the ported Caffe, almost everything in Caffe is successfully ported to Android platform except the underlying data format support, i.e. leveldb, hdf5, etc. You can refer to https://github.com/sh1r0/caffe/blob/mobile/Makefile.mobile#L77-82 for details.

Please let me know if you have any further questions.

Thanks,
-shiro

**Comment by jbeorse** [comment]
Great. Thank you for the licensing information and details on the port. I will let you know if I have further issues or if I add something that you might want to merge.
