### ISSUE TITLE
build_boost.sh contains absolute path cause compile failed

### ISSUE THREAD

**Issue by zhenzhang20** [sh1r0/caffe-android-lib#25]
in file : ~/caffe-android-lib/scripts/build_boost.sh
it contains : 
     cmake -DCMAKE_TOOLCHAIN_FILE="~/test/caffe-android-lib/android-cmake/androi..........

I think it should be :
     cmake -DCMAKE_TOOLCHAIN_FILE="${WD}/android-cmake

Else, some build error will pop up like:

Make Error at /usr/local/share/cmake-3.2/Modules/CMakeDetermineSystem.cmake:104 (message):
  Could not find toolchain file:
  ~/test/caffe-android-lib/android-cmake/android.toolchain.cmake
Call Stack (most recent call first):
  CMakeLists.txt:3 (project)

CMake Error: Error required internal CMake variable not set, cmake may be not be built correctly.
Missing variable is:
CMAKE_C_COMPILER_ENV_VAR
CMake Error: Error required internal CMake variable not set, cmake may be not be built correctly.
Missing variable is:
CMAKE_C_COMPILER
CMake Error: Could not find cmake module file: /home/zz/compile/caffe-android-lib/boost/build/CMakeFiles/3.2.2/CMakeCCompiler.cmake
CMake Error: Error required internal CMake variable not set, cmake may be not be built correctly.
Missing variable is:
CMAKE_CXX_COMPILER_ENV_VAR

**Comment by sh1r0** [comment]
It was reported (https://github.com/sh1r0/caffe-android-lib/issues/24) and solved (https://github.com/sh1r0/caffe-android-lib/commit/2c6ce9b6e659ba245aee0b247d1b7722742e8907).
