### ISSUE TITLE
build_protobuf.sh contains absolute path cause compile failed

### ISSUE THREAD

**Issue by zhenzhang20** [sh1r0/caffe-android-lib#26]
in file : ~/caffe-android-lib/scripts/build_protobuf.sh
it contains : 
cmake -DCMAKE_TOOLCHAIN_FILE=~/android-cmake/android.toolchain.cmake..........

I think it should be :
cmake -DCMAKE_TOOLCHAIN_FILE=="${WD}/android-cmake/android.toolchain.cmake"....

Else, some build error will pop up

**Comment by sh1r0** [comment]
It was reported (https://github.com/sh1r0/caffe-android-lib/issues/24) and solved (https://github.com/sh1r0/caffe-android-lib/commit/2c6ce9b6e659ba245aee0b247d1b7722742e8907).
