### ISSUE TITLE
Network outputs

### ISSUE THREAD

**Issue by Mozie2341** [sh1r0/caffe-android-lib#29]
Heya,

Might be a bit offtopic, but I'm trying to use a model based on GoogleNet with your lib and it's giving me an error: Caffe: Check failed: net_->num_outputs() == 1 Network should have exactly one output.

Probably has little to do with the lib and moreso with me, any ideas?

**Comment by sh1r0** [comment]
Please use [this](https://github.com/BVLC/caffe/blob/master/models/bvlc_googlenet/deploy.prototxt). Thanks.

**Comment by Mozie2341** [comment]
Looking at the last layer of my model showed multiple outputs compared to what you linked, thanks!
