### ISSUE TITLE
omp_set_num_threads didnot work?

### ISSUE THREAD

**Issue by wuxuewu** [sh1r0/caffe-android-lib#33]
Hi sh1r0: 
in the `caffe_jni.cpp`, I use `omp_set_num_threads(4)`,then follow with `omp_get_max_threads()`,and the result is 4,it's ok.But when I call `omp_get_max_threads()` in the function `predict_top_k()` in the file of `caffe_mobile.cpp`, the result is 8 ( 8 core inside). that's so weird.
Then I use `Eigen::setNbThreads(4)` in the `caffe_jni.cpp`, and call `Eigen::nbThreads()` in `caffe_mobile.cpp` like this:

`VLOG(1)<<Eigen::nbThreads();`
`const vector<Blob<float>*>& result = caffe_net->Forward(dummy_bottom_vec, &loss);`
`VLOG(1)<<Eigen::nbThreads();`

the results are 4,it's right. But in the lib of eigen, the function `parallelize_gemm`,calls `nbThreads()`, and the results are 8... it actually runs in 8 threads...

it seems that the action scope of the layer jni and the layer in the eigen is not the same...
Does anyone have some idea?

**Comment by sh1r0** [comment]
Since I deprecated the support of Eigen, this issue is gonna be closed.
