### ISSUE TITLE
How to get the confidence of my prediction?

### ISSUE THREAD

**Issue by cmaciasporta** [sh1r0/caffe-android-lib#34]
For example in python I do:

prediction = mNet.predict([image])
print prediction

And the output is:
[[ 0.32693869  0.20242123  0.26447725  0.20616281]]

How do I get it on caffe-mobile?

Thanks, you are doing a great work!!

**Comment by cmaciasporta** [comment]
I added to caffe_jni.cpp the following lines:
JNIEXPORT jfloatArray JNICALL
Java_com_sh1r0_caffe_1android_1lib_CaffeMobile_getConfidence(JNIEnv *env,
                                                            jobject thiz,
                                                            jstring imgPath) {
  CaffeMobile *caffe_mobile = CaffeMobile::Get();
  vector<float> confidence = caffe_mobile->GetConfidence(jstring2string(env, imgPath));

  jfloatArray result;
  result = env->NewFloatArray(4);
  if (result == NULL) {
    return NULL; /* out of memory error thrown */
  }
  // move from the temp structure to the java structure
  env->SetFloatArrayRegion(result, 0, 4, &confidence[0]);
  return result;
}


Then added to caffe_mobile.cpp 

vector<float> CaffeMobile::GetConfidence(const string &img_path) {
  const vector<float> probs = Forward(img_path);
  return probs;
}

And created a native method on android. But it returns the following code ( I have 4 classes):
label 0 = 0.0
label 1 = 1.0
label 2 = 0.0
label 3 = 0.0

Another prediction:
label 0 = 0.0
label 0 = 0.0
label 0 = 0.0
label 0 = 1.0

So, it gives not gives to me the confidence that I want. Am I doing something wrong? Or is not possible?

**Comment by g1910** [comment]
Hi,
We are trying to build an app which requires to classify objects based on whether the confidence value is higher than a threshold. This work of yours looks really promising and we would like to go forward with using it. Problem is that we really need the individual confidence values. Please see if this functionality can be added asap.

Else, it seems that only the .so is accessible in the recent commits and not the .cpp code which we can ourselves modify. See if you can re-add in the upcoming commits.

**Comment by sh1r0** [comment]
I have updated the [dev](https://github.com/sh1r0/caffe-android-lib/tree/dev) branch with `GetConfidenceScore` function in caffe_mobile module. The source files are right [here](https://github.com/sh1r0/caffe/tree/cmake_android/android).
Please have a try and kindly let me know if there is any problem. Thanks.

**Comment by g1910** [comment]
I can see the changes in the .cpp files. But, how to get them reflected in the java class?

Please update the caffe-android-demo project with these changes. Also, please add some documentation on how to get the functionality from .cpp to .java.
