### ISSUE TITLE
Why does JNI code require armeabi-v7a-hard-softfp and not armeabi-v7a-hard- ABI?

### ISSUE THREAD

**Issue by jainanshul** [sh1r0/caffe-android-lib#37]
Reference: https://github.com/sh1r0/android-cmake/commit/20adf29a4ae6960f87f395989768935e54b1f529

**Comment by sh1r0** [comment]
https://groups.google.com/forum/#!msg/android-ndk/NbUq9FDDZOo/TJJsAS6nM7wJ

**Comment by jainanshul** [comment]
Thanks @sh1r0 as per the link above JNI functions should be compiled with softfp but armeabi-v7a-hard-softfp still sets the ABI to armeabi-v7a-hard and CXXFLAGS to -mhard-float. The only difference being the flag -D_NDK_MATH_NO_SOFTFP=1, which I am not sure how it helps in this case?

**Comment by sh1r0** [comment]
Please refer to `tests/device/hard-float/jni/Android.mk` in Android NDK.

**Comment by jainanshul** [comment]
I did and I understand the meaning of D_NDK_MATH_NO_SOFTFP=1 but I am not sure why is that needed to compile JNI code. Why can't armeabi-v7a-hard be used to compile JNI code. It seems like someone was able to compile the JNI code with armeabi-v7a-hard with NEON at https://github.com/sh1r0/caffe-android-lib/issues/27#issuecomment-167722576. So my original question still remains, why armeabi-v7a-hard-softfp and not armeabi-v7a-hard?

**Comment by sh1r0** [comment]
Sorry, per my previous tests, the current setup is the only way I can successfully make it. I guessed the key point is that JNI somehow needs softfp instead of hardfp. But if you succeed in making everything work by simply using armeabi-v7a-hard, please kindly let me know (PR is also welcome). Thanks.

**Comment by jainanshul** [comment]
But again armeabi-v7a-hard-softfp that are using is still using hardfp with the exception on using libm for soft abi math functions. If JNI needs softfp then we should compile JNI code with softfp and not with armeabi-v7a-hard-softfp or armeabi-v7a-hard.

Thanks anyways. My setup is a little different where I don't have any JNI code but was trying to use openblas with softfp on ARM7 as rest of my system is softfp but OpenBLAS crashes on me. I have other libraries that are dependent on OpenCV for example so I can't compile opencv with hardfloat without breaking these other modules which would be required if I am compiling Caffe and OpenBLAS with hardfloat. I don't want to compile two copies of opencv one with softfp for other softfp module and hardffp for caffe and OpenBLAS.

Do you know of a way to call from softfp based library using floating point to call into Caffe compiled with  hardfp? The link you mentioned says that adding 
```__attribute__((pcs("aapcs")))``` is to tell to the compiler how a function expect to receive its arguments so it won't help unless I change the Caffe code to add this attribute to all the functions taking or returnign floats.

**Comment by sh1r0** [comment]
If you hope have everything with softfp, you can build openblas with ARMv5 as a workaround.

**Comment by jainanshul** [comment]
Do you know if ARMv5 OpenBLAS is compatible with ARMv7 based chipsets?

**Comment by sh1r0** [comment]
Yes, please refer to https://github.com/sh1r0/caffe-android-lib/blob/dev/scripts/build_openblas.sh.

**Comment by jainanshul** [comment]
Thank you, will give that a try. Appreciate all your help. Your project was immensely helpful to me.
