### ISSUE TITLE
Estimate of work for integrating data layer, solver, etc

### ISSUE THREAD

**Issue by jbeorse** [sh1r0/caffe-android-lib#4]
You advised me that the remaining portions of caffe that were not integrated into caffe-android-lib were as follows: 

\# src/caffe/layers/data_layer.cpp \
\# src/caffe/layers/hdf5_data_layer.cpp \
\# src/caffe/layers/hdf5_output_layer.cpp \
\# src/caffe/solver.cpp \
\# src/caffe/util/db.cpp \
\# src/caffe/util/math_functions.cpp

My project needs image_data_layer and thus data_layer, and we also use solvers. Do you have an idea of how much work would be required to be able to include the missing files? Is it just a matter of building hdf5 for Android? Have you attempted this and run into troubles? 

Thanks,
Jeff

EDIT: What changes do I need to make to start trying to build these files and seeing the proper errors? I added them to Android.mk and got errors along the lines of:
```bash
/home/jbeorse/workspace/caffe-android-lib/caffe-mobile/jni/caffe/src/caffe/layers/data_layer.cpp:20:1: error: 'DataLayer' does not name a type
 DataLayer<Dtype>::~DataLayer<Dtype>() {
```
Which makes me assume I haven't included everything properly.

**Comment by sh1r0** [comment]
I just updated the repo, now solver is compiled together with Caffe-Mobile. If you need image_data_layer only, there's no need to make data_layer.cpp included in Makefile, this android lib always supports it. (I used image_data to deploy on mobile before, and now memory_data is used.)
If you really want all those ignored stuff to get back, you probably need to cross compile not only hdf5 but also leveldb and lmdb.

Thanks.

**Comment by jbeorse** [comment]
Thanks for the quick response and updates.

Hmm, I'm actually integrating code that was written by a partner and I don't fully know all of its inner workings. I'm not trying to train on Android, but its certainly possible I've missed some things when trying to remove that code. 

I believe we'll need to use lmdb, so I'll be looking into compiling that for Android. If I have success I'll let you know. 

On a side note, I'm a little confused with how you are using glog and gflags. You don't seem to be building them for Android, and in fact I see an area where you use glog_alternative.hpp, but then there are files like [caffe-android-lib/caffe-mobile/jni/caffe/tools/compute_image_mean.cpp](https://github.com/sh1r0/caffe/blob/b7a5b5d09ed739be3609b3262065b90a0e6cd999/tools/compute_image_mean.cpp) that still include \<glog/logging.h\>. How does this work?

**Comment by sh1r0** [comment]
In short, I avoid using glog and gflags in porting.
Tools are not used in my case, thus they are excluded. (In [Android.mk](https://github.com/sh1r0/caffe-android-lib/blob/master/caffe-mobile/jni/Android.mk), only things under  src/caffe/ are included for compilation.) `glog_alternative.hpp` is a simple wrapper with `CHECK*` macros taking place of glog ones.

Thanks.

**Comment by jbeorse** [comment]
Ok, that makes sense. I'm working on creating a header that translates glog calls into native Android logger calls. If I get that working I'll share that with you.
