### ISSUE TITLE
Different classification result because of deploy.prototxt?

### ISSUE THREAD

**Issue by lidaweironaldo** [sh1r0/caffe-android-lib#40]
I tried to classify some imageNet image using AlexNet and it gives different result using deploy.prototxt and train_test.prototxt. Is it because in train_test.prototxt, it uses a crop_size 277 in transform_param but not used in deploy.prototxt or deploy_mobile.prototxt?

**Comment by sh1r0** [comment]
`train_test.prototxt`? Did you mean `train_val.prototxt`? The `train_val`-like prototxts should have problems in loading by `caffe_mobile`. Could you provide your test procedures?

**Comment by lidaweironaldo** [comment]
I found that it is the "Preprocess" function in caffe_mobile.cpp. This function just resizes an input image instead of cropping it (i.e., center cropping as used in "TEST" phase).
