### ISSUE TITLE
Caffe-android-lib fail in Mac OS

### ISSUE THREAD

**Issue by fh127** [sh1r0/caffe-android-lib#41]
Hi, 

I need ti integrate caffe library in my Android project to import classes in C source using NDK, when I try to build this library in Mac Os, I have the next error

          readlink: illegal option -- f
          usage: readlink [-n] [file ..

Can you help me?

**Comment by sh1r0** [comment]
You have to install gnu coreutils, for example, `brew install coreutils`.

**Comment by tuanchauict** [comment]
For me, after install coreutils, I have to change all `readlink` in the scripts into `greadlink` because it is a `/usr/bin/readlink` in macOS Sierra (although I set alias `readlink=greadlink`

**Comment by cxy200927099** [comment]
@sh1r0 I also get the error,my command as bellow:
1.  excute:  
```
git clone --recursive https://github.com/sh1r0/caffe-android-lib.git
```
2.  excute:  
```
cd caffe-android-lib
```
3.  excute:  
```
export ANDROID_ABI="arm64-v8a" # Optional, see the note below
```
4. excute:  
```
./build.sh /Users/chenxingyi/work/Android/package/sdk/ndk-bundle/
```
and "/Users/chenxingyi/work/Android/package/sdk/ndk-bundle/" is my ndk path
5. 
```
brew install coreutils
alias readlink=greadlink
```
6. exute .
```
./build.sh /Users/chenxingyi/work/Android/package/sdk/ndk-bundle/
```
but is still get the error:
```
      readlink: illegal option -- f
      usage: readlink [-n] [file ..
```

my computer is macOS Sierra 10.12.6, i am a fresher for deep learning, please help me, thank you!

**Comment by cxy200927099** [comment]
I find the solution:
1.install coreutils：
```
brew install coreutils
```
2.set envionment variables，edit ~/.bash_profile or ~/.zshrc，add：
```
export PATH=/usr/local/opt/coreutils/libexec/gnubin:$PATH
alias readlink=greadlink
```
