### ISSUE TITLE
compile caffe-android-lib with a cv::SVM

### ISSUE THREAD

**Issue by mgarbade** [sh1r0/caffe-android-lib#43]
Hey

I'm quite interested in your code, thanks for sharing it. I wanted to use a self trained opencv support vector machine (cv::SVM) for classfiying images.

I added some cv::SVM to the `CaffeMobile.cpp` file. However for compiling the code I need to call 
`    ./build.sh <path/to/ndk>`
Unfortunately it gives me an error saying:
`error: undefined reference to 'cv::ml::SVM::create()'`

or more detailed:

`CMakeFiles/caffe_jni.dir/caffe_mobile.cpp.o:caffe_mobile.cpp:function cv::Ptr<cv::ml::SVM> cv::Algorithm::load<cv::ml::SVM>(cv::String const&, cv::String const&): error: undefined reference to 'cv::ml::SVM::create()'`
`CMakeFiles/caffe_jni.dir/caffe_mobile.cpp.o:caffe_mobile.cpp:function caffe::CaffeMobile::CaffeMobile(std::string const&, std::string const&): error: undefined reference to 'cv::ml::SVM::create()'
collect2: error: ld returned 1 exit status
make[2]: *** [lib/libcaffe_jni.so] Error 1
make[1]: *** [android/CMakeFiles/caffe_jni.dir/all] Error 2
make: *** [all] Error 2
`
I guess I need to link `opencv_ml` somewhere, but I don't really understand how the compiling is done, so I don't know where I should add this library for the building process.

Can you help me / give me a hint how to do that?
Any help would be appreciated.

**Comment by sh1r0** [comment]
Please refer to [here](https://github.com/sh1r0/caffe/blob/cmake_android/cmake/Dependencies.cmake#L78-L88), and you might need to add `ml` module in `find_package`.

**Comment by mgarbade** [comment]
Thanks a lot! It compiles now :). 
Do you also know how I could use the updated version of `caffe-android-lib` in your `caffe-android-demo` ? 
I guess I need to replace `libcaffe.so` and `libcaffe_jni.so` ? 
Is there more to do?

**Comment by mgarbade** [comment]
All is working now! Thanks again for your help :-)

**Comment by sh1r0** [comment]
:+1:
