### ISSUE TITLE
Build libs crashing the android app from https://github.com/sh1r0/caffe-android-demo

### ISSUE THREAD

**Issue by rivaldo4t** [sh1r0/caffe-android-lib#44]
The Android app works fine with the libraries already in the package but when I use the libraries built with https://github.com/sh1r0/caffe-android-lib the app crashes in the caffeMobile.loadModel method.

**Comment by sh1r0** [comment]
The pre-built libs in [caffe-android-demo](https://github.com/sh1r0/caffe-android-demo) are built on the [dev](https://github.com/sh1r0/caffe-android-lib/tree/dev) branch.

**Comment by rivaldo4t** [comment]
Okay. Thanks. Why won't the libs built on master branch work?

**Comment by sh1r0** [comment]
Basically, the caffe lib in master is outdated. For details, please refer to https://github.com/sh1r0/caffe-android-lib/compare/master...dev.

**Comment by rivaldo4t** [comment]
Thanks again. Huge help.

**Comment by rivaldo4t** [comment]
I built the caffe-android-lib from the dev branch. It is also creating one libcaffe.so.1.0.0-rc3 file which the master was not generating. The app still crashes even though I push libcaffe.so and libcaffe_jni.so along with the above file. Can you tell the reason? I am using the master branch caffe-android-demo and i get the following error - 
E/art     (27830): dlopen("/data/app/com.sh1r0.caffe_android_demo-2/lib/arm/libcaffe_jni.so", RTLD_LAZY) failed: dlopen failed: library "libcaffe.so.1.0.0-rc3" not found
