### ISSUE TITLE
Cannot build - boost_chrono not found

### ISSUE THREAD

**Issue by sladomic** [sh1r0/caffe-android-lib#45]
Hi

I desperately tried to build the caffe-android-lib for arm64-v8a architecture but always get this error (I tried with both master and dev branch). I build on OSX El Capitan, ndk-r10e.

`CMake Error at /usr/local/Cellar/cmake/3.5.0/share/cmake/Modules/FindBoost.cmake:1647 (message):
  Unable to find the requested Boost libraries.

  Boost version: 1.56.0

  Boost include path:
  /Users/sladomic/caffe-android-lib/android_lib/boost/include

  Could not find the following Boost libraries:

          boost_chrono

  Some (but not all) of the required Boost libraries were found.  You may
  need to install these additional Boost libraries.  Alternatively, set
  BOOST_LIBRARYDIR to the directory containing Boost libraries or BOOST_ROOT
  to the location of Boost.
Call Stack (most recent call first):
  cmake/Dependencies.cmake:5 (find_package)
  CMakeLists.txt:63 (include)

-- Found GFlags: /Users/sladomic/caffe-android-lib/android_lib/gflags/include  
-- Found gflags  (include: /Users/sladomic/caffe-android-lib/android_lib/gflags/include, library: /Users/sladomic/caffe-android-lib/android_lib/gflags/lib/libgflags.a)
-- Found PROTOBUF: /Users/sladomic/caffe-android-lib/android_lib/protobuf/lib/libprotobuf.a  
-- Found PROTOBUF Compiler: /Users/sladomic/caffe-android-lib/android_lib/protobuf_host/bin/protoc
-- Found LMDB: /Users/sladomic/caffe-android-lib/android_lib/lmdb/include  
-- Found lmdb    (include: /Users/sladomic/caffe-android-lib/android_lib/lmdb/include, library: /Users/sladomic/caffe-android-lib/android_lib/lmdb/lib/liblmdb.a)
-- -- CUDA is disabled. Building without it...
-- OpenCV found (/Users/sladomic/caffe-android-lib/android_lib/opencv/sdk/native/jni)
-- Found EIGEN include: /Users/sladomic/caffe-android-lib/android_lib/eigen3
-- Python interface is disabled or not all required dependencies found. Building without it...
-- Could NOT find Git (missing:  GIT_EXECUTABLE) 
-- 
-- ******************* Caffe Configuration Summary *******************
-- General:
--   Version           :   1.0.0-rc3
--   Git               :   unknown
--   System            :   Android
--   C++ compiler      :   /Users/sladomic/Library/Android/sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-g++
--   Release CXX flags :   -mthumb -fomit-frame-pointer -fno-strict-aliasing -O3 -DNDEBUG -fexceptions -frtti -Wno-psabi --sysroot=/Users/sladomic/Library/Android/sdk/ndk-bundle/platforms/android-21/arch-arm -funwind-tables -finline-limit=64 -fsigned-char -no-canonical-prefixes -march=armv7-a -mfloat-abi=softfp -mfpu=neon -fdata-sections -ffunction-sections -Wa,--noexecstack -fopenmp  -std=c++11 -fPIC -Wall -Wno-sign-compare -Wno-uninitialized
--   Debug CXX flags   :   -marm -fno-omit-frame-pointer -fno-strict-aliasing -O0 -g -DDEBUG -D_DEBUG -fexceptions -frtti -Wno-psabi --sysroot=/Users/sladomic/Library/Android/sdk/ndk-bundle/platforms/android-21/arch-arm -funwind-tables -finline-limit=64 -fsigned-char -no-canonical-prefixes -march=armv7-a -mfloat-abi=softfp -mfpu=neon -fdata-sections -ffunction-sections -Wa,--noexecstack -fopenmp  -std=c++11 -fPIC -Wall -Wno-sign-compare -Wno-uninitialized
--   Build type        :   Release
-- 
--   BUILD_SHARED_LIBS :   ON
--   BUILD_python      :   OFF
--   BUILD_matlab      :   OFF
--   BUILD_docs        :   OFF
--   CPU_ONLY          :   ON
--   USE_OPENCV        :   ON
--   USE_LEVELDB       :   OFF
--   USE_LMDB          :   ON
--   ALLOW_LMDB_NOLOCK :   OFF
--   USE_HDF5          :   OFF
--   USE_GLOG          :   OFF
-- 
-- Dependencies:
--   BLAS              :   Yes (eigen)
--   Boost             :   Yes (ver. 1.56)
--   gflags            :   Yes
--   protobuf          :   Yes (ver. 3.0.0)
--   lmdb              :   Yes (ver. 0.9.70)
--   OpenCV            :   Yes (ver. 3.1.0)
--   CUDA              :   No
-- 
-- Install:
--   Install path      :   /Users/sladomic/caffe-android-lib/android_lib/caffe
-- 
-- Configuring incomplete, errors occurred!
See also "/Users/sladomic/caffe-android-lib/caffe/build/CMakeFiles/CMakeOutput.log".`

Can I somehow copy the boost_chrono from somewhere else or do I need to change something in the build script?

Thanks,
Michael

**Comment by sh1r0** [comment]
I just had a test build of dev branch on my macbook (OS X El Capitan) using cmake 3.5.2 and ndk-r10e, and everything seemed fine. Please make sure your settings are correct, e.g.,
```shell
export ANDROID_ABI="arm64-v8a"
export USE_OPENBLAS=1
```
Thanks.

**Comment by sladomic** [comment]
Thanks. It worked now. I updated my cmake from 3.5.0 to 3.5.2 and used OpenBLAS now. But nevertheless the issue https://github.com/sh1r0/caffe-android-demo/issues/20 remains. This one can be closed though.
