### ISSUE TITLE
Questions: How correcly add it to JNI, the Compiler flag CPU_ONLY = ON is not working.

### ISSUE THREAD

**Issue by AndriusRimk** [sh1r0/caffe-android-lib#46]
HI,
I have android.mk file and source code uses the cafe.
Adding cafe .so library as include $(PREBUILT_SHARED_LIBRARY).
And to module adding the Header files.

But always i am getting error that:
`     [exec] ../../../ext/caffe/android/include/caffe/util/device_alternate.hpp:34:23: fatal error: cublas_v2.h: No such file or directory
     [exec]  #include <cublas_v2.h>`

So i understand that CPU_ONLY=ON don`t transwer so i added for android and application mk files.
```
APP_CPPFLAGS := -CPU_ONLY=ON
LOCAL_CPPFLAGS := -CPU_ONLY=ON
```

But still getting the same error. Maybe i am doing something wrong ?

Thanks in Advance.

**Comment by sh1r0** [comment]
It should be `-DCPU_ONLY` (without `=ON`).

**Comment by sh1r0** [comment]
Any further progress? Or this should be closed.

**Comment by AndriusRimk** [comment]
Yes, it can be closed.
Thanks for your answer this part i solved, but for some reason i only could applie this to `APP_CPPFLAGS ` to work.

**Comment by sh1r0** [comment]
Hi @AndriusRimk, I've created a [sample](https://gist.github.com/sh1r0/0ee4b83addf06157f3f5bcfc9294a082) for using prebuilt caffe libs in a ndk project. The sample works for me to build caffe_jni with ndk-build.
