### ISSUE TITLE
How to access data from android camera without storing them to some jpg file?

### ISSUE THREAD

**Issue by mgarbade** [sh1r0/caffe-android-lib#48]
I'm running a detector based on your caffe version. I'd like to increase the detection speed by passing the data from camera to caffe without the intermediate storing to SD-Card step. Can you point me a way how to do that?
In turn (if you are interested) I could share my code for running my detector on android in turn once the code is little more sophisticated / readable.

For starting I guess I would have to replace the string variable `jstring imgPath` in `caffe_jni.cpp`  line 88 by a pointer pointing to the location of the image in the RAM memory of the smartphone
```
JNIEXPORT jintArray JNICALL
Java_com_demoDetectorApp_caffe_1android_1lib_CaffeMobile_predictImage(JNIEnv *env,
                                                            jobject thiz,
                                                            jstring imgPath,
                                                            jint k) {
```

Then I would need to store tthe image as a opencv Mat object. I know how to go on from there. (Basically one needs to copy the opencv Mat into the `blob[0]` object of the caffe network).

For any hints / advice I would be very grateful!

**Comment by sh1r0** [comment]
Hi @mgarbade, it's possible to directly use frame buffer (in YUV-NV21 format for camera preview) as input with 29e8092 on dev branch.

**Comment by mgarbade** [comment]
Thanks for your reply. What is `29e8092 on dev branch` ? Is this another fork of `caffe-android-lib`? If yes where can I download it? There is nothing to download when I follow this link above (neither when I look for it elsewhere in the git-repository)...  
(Sorry for the stupid question ;) )

**Comment by sh1r0** [comment]
It's on [dev](https://github.com/sh1r0/caffe-android-lib/tree/dev) branch.
