### ISSUE TITLE
forwarding consumes too much memory

### ISSUE THREAD

**Issue by westpilgrim** [sh1r0/caffe-android-lib#49]
hello , I have a dnn model whose size is only 30M~40M,but when I use your lib to do the forwarding ,the memory consumption reach an unacceptible peak 2G~3G .

could it be that I may not use it in a correct way? or is it the inborn problem of caffe?

**Comment by sh1r0** [comment]
Could you have a try using the desktop?

**Comment by westpilgrim** [comment]
I tested on a desktop ,the memory consumption is similar

**Comment by westpilgrim** [comment]
I solved it by change a bigger memory
