### ISSUE TITLE
What is the progress on OpenCL support?

### ISSUE THREAD

**Issue by rivaldo4t** [sh1r0/caffe-android-lib#50]
Have you started development for OpenCL support on Android.

**Comment by rivaldo4t** [comment]
How should one proceed for the same. Will https://github.com/amd/OpenCL-caffe help??

**Comment by malzantot** [comment]
have you checked this issue ?
https://github.com/sh1r0/caffe-android-lib/issues/23 

There is a branch for OpenCL support on Android. However,  when I compiled and attempted to run it on the mobile device, It fails while parsing the "deploy.prototxt" net file.

**Comment by sh1r0** [comment]
As @malzantot mentioned, please refer to #23.
