### ISSUE TITLE
android.mk 设置

### ISSUE THREAD

**Issue by dadaxxxx** [sh1r0/caffe-android-lib#51]
hi,I got a problem.
./caffe/include/caffe/util/device_alternate.hpp:34:23: fatal error: cublas_v2.h: No such file or directory

what can i do to solve this problem.

**Comment by sh1r0** [comment]
Please refer to https://github.com/sh1r0/caffe-android-demo/issues/25#issuecomment-222347232.

**Comment by dadaxxxx** [comment]
hi ,the sample link you offered is unreachable，https://gist.github.com/sh1r0/0ee4b83addf06157f3f5bcfc9294a082。can you offer a sample link。3q very much........

**Comment by sh1r0** [comment]
The link works (tested in private window).

**Comment by dadaxxxx** [comment]
i mean that in question 25 you answers : I've created a sample for using prebuilt caffe libs in a ndk project. The sample works for me to build caffe_jni with ndk-build.

    but when i click the sample link it is unreachable. can you help me....

**Comment by sh1r0** [comment]
I knew it, and https://gist.github.com/sh1r0/0ee4b83addf06157f3f5bcfc9294a082 do work for me.

**Comment by dadaxxxx** [comment]
i am sorry to bother you again.  it is still unreachable, can you copy the android.mk information in here.

thanks very much

**Comment by sh1r0** [comment]
Here you are.

The sample project structure is shown below.
```shell
.
├── android_lib
├── jni
│   ├── Android.mk
│   ├── Application.mk
│   ├── caffe_jni.cpp
│   ├── caffe_mobile.cpp
│   └── caffe_mobile.hpp
└── prebuilt
    ├── arm64-v8a
    ├── armeabi
    ├── armeabi-v7a
    ├── x86
    └── x86_64
```

Android.mk
======
```mk
LOCAL_PATH := $(call my-dir)

# C++ full library
# =======================================================
include $(CLEAR_VARS)
LOCAL_MODULE := caffe
LOCAL_SRC_FILES := $(LOCAL_PATH)/../prebuilt/$(TARGET_ARCH_ABI)/libcaffe.so
include $(PREBUILT_SHARED_LIBRARY)

#-----------------------------------------------------------------------------
include $(CLEAR_VARS)
LOCAL_MODULE := caffe_jni

LOCAL_SRC_FILES := caffe_jni.cpp caffe_mobile.cpp
LOCAL_C_INCLUDES := $(LOCAL_PATH)/../android_lib/caffe/include \
                    $(LOCAL_PATH)/../android_lib/boost/include \
                    $(LOCAL_PATH)/../android_lib/gflags/include \
                    $(LOCAL_PATH)/../android_lib/glog/include \
                    $(LOCAL_PATH)/../android_lib/protobuf/include \
                    $(LOCAL_PATH)/../android_lib/openblas/include \
                    $(LOCAL_PATH)/../android_lib/opencv/sdk/native/jni/include

LOCAL_SHARED_LIBRARIES := caffe
LOCAL_LDLIBS := -lm -llog
LOCAL_CPPFLAGS += -fexceptions -frtti -std=c++11 -DCPU_ONLY

include $(BUILD_SHARED_LIBRARY)
```

Application.mk
======
```mk
NDK_TOOLCHAIN_VERSION := 4.9
APP_PLATFORM := android-21
APP_STL := gnustl_static
APP_ABI := armeabi armeabi-v7a x86 arm64-v8a x86_64
APP_MODULE := libcaffe_jni
```

**Comment by dadaxxxx** [comment]
hi,when i usr your android.mk , the mistakes is solved ,but it occurs 
./../android_lib/boost/include/boost/system/error_code.hpp:221: error: undefined reference to 'boost::system::generic_category()'
./../android_lib/boost/include/boost/system/error_code.hpp:222: error: undefined reference to 'boost::system::generic_category()'
./../android_lib/boost/include/boost/system/error_code.hpp:223: error: undefined reference to 'boost::system::system_category()'
collect2: error: ld returned 1 exit status

the boost is in android_lib,do you know why?

**Comment by sh1r0** [comment]
Please provide more details, e.g., what abi did you use, how did you get the prebuilt libs, which api level did you use, what would you like to build, etc. Thanks.

**Comment by sh1r0** [comment]
Should be closed?

**Comment by hpsaturn** [comment]
Hi,

I have the same problem, but I not use MakeFiles o "normal" NDK-JNI project, I implement CMake for compile my project. When I going to include Caffe with script like this:

`#!/usr/bin/env sh
set -e

if [ -z "$NDK_ROOT" ] && [ "$#" -eq 0 ]; then
    echo 'Either $NDK_ROOT should be set or provided as argument'
    echo "e.g., 'export NDK_ROOT=/path/to/ndk' or"
    echo "      '${0} /path/to/ndk'"
    exit 1
else
    NDK_ROOT="${1:-${NDK_ROOT}}"
fi

ANDROID_ABI=${ANDROID_ABI:-"armeabi-v7a with NEON"}
WD=$(readlink -f "`dirname $0`/..")

MATRIX_ROOT=${WD}/matrix
BUILD_DIR=$MATRIX_ROOT/build

ANDROID_LIB_ROOT=${WD}/android_lib
BOOST_HOME=${ANDROID_LIB_ROOT}/boost
GFLAGS_HOME=${ANDROID_LIB_ROOT}/gflags
GLOG_ROOT=${ANDROID_LIB_ROOT}/glog
OPENCV_ROOT=${ANDROID_LIB_ROOT}/opencv/sdk/native/jni
PROTOBUF_HOST_ROOT=${ANDROID_LIB_ROOT}/protobuf_host
PROTOBUF_ROOT=${ANDROID_LIB_ROOT}/protobuf
GTEST_LIB_ROOT=${WD}/googletest/googletest
GTEST_ROOT=${ANDROID_LIB_ROOT}/googletest
CAFFE_ROOT=${ANDROID_LIB_ROOT}/caffe
APP_PLATFORM="android-9"
export LMDB_DIR=${ANDROID_LIB_ROOT}/lmdb
export OpenBLAS_HOME="${ANDROID_LIB_ROOT}/openblas"


INSTALL_DIR=${WD}/android_lib
N_JOBS=${N_JOBS:-4}

ASFLAGS="-D__ANDROID__"

if [ "${ANDROID_ABI}" = "armeabi" ]; then
    API_LEVEL=19
else
    API_LEVEL=21
fi

rm -rf "${BUILD_DIR}"
mkdir -p "${BUILD_DIR}"
cd "${BUILD_DIR}"

cmake -DCMAKE_TOOLCHAIN_FILE="${WD}/android-cmake/android.toolchain.cmake" \
      -DANDROID_NDK="${NDK_ROOT}" \
      -DCMAKE_BUILD_TYPE=Debug \
      -DANDROID_ABI="${ANDROID_ABI}" \
      -DANDROID_NATIVE_API_LEVEL=21 \
      -DANDROID_USE_OPENMP=ON \
      -DADDITIONAL_FIND_PATH="${ANDROID_LIB_ROOT}" \
      -DGTEST_INCLUDE_DIR="{$GTEST_ROOT}/include" \
      -DGTEST_LIBRARY="${GTEST_ROOT}/lib/libgtest.a" \
      -DGTEST_MAIN_LIBRARY="${GTEST_ROOT}/lib/libgtest_main.a" \
      -DGTEST_ROOT="${GTEST_ROOT}" \
      -DBOOST_ROOT="${BOOST_HOME}" \
      -DGFLAGS_ROOT="${GFLAGS_HOME}" \
      -DGFLAGS_INCLUDE_DIR="${GFLAGS_ROOT}/include" \
      -DGFLAGS_LIBRARY="${GFLAGS_ROOT}/lib/libgflags.a" \
      -DGLOG_ROOT="${GLOG_ROOT}" \
      -DGLOG_INCLUDE_DIR="${GLOG_ROOT}/include" \
      -DGLOG_LIBRARY="${GLOG_ROOT}/lib/libglog.a" \
      -DOpenCV_DIR="${OPENCV_ROOT}" \
      -DPROTOBUF_ROOT="${PROTOBUF_ROOT}" \
      -DPROTOBUF_HOST_ROOT="${PROTOBUF_HOST_ROOT}" \
      -DPROTOBUF_PROTOC_EXECUTABLE="${ANDROID_LIB_ROOT}/protobuf_host/bin/protoc" \
      -DPROTOBUF_INCLUDE_DIR="${PROTOBUF_ROOT}/include" \
      -DPROTOBUF_LIBRARY="${PROTOBUF_ROOT}/lib/libprotobuf.a" \
      -DOPENBLAS_ROOT="${OpenBLAS_HOME}" \
      -DCAFFE_ROOT="${CAFFE_ROOT}" \
      -DCAFFE_LIBRARY="${CAFFE_ROOT}/lib/libcaffe.a" \
      -DCAFFE_INCLUDE_DIR="${CAFFE_ROOT}/include" \
      -DCMAKE_INSTALL_PREFIX="${ANDROID_LIB_ROOT}/matrix" \
      ..

make -j${N_JOBS}
rm -rf "${INSTALL_DIR}/matrix"
make install/strip

cd "${WD}"
`
afeter include <caffe/net.hpp> the output is :
~/src/caffe-android-lib/android_lib/caffe/include/caffe/util/device_alternate.hpp:34:23: fatal error: cublas_v2.h: No such file or directory

**Comment by sh1r0** [comment]
@hpsaturn, you did not set `CPU_ONLY` flag.

**Comment by hpsaturn** [comment]
thanks @sh1r0 !!

fix for cmake:
```cmake
set (CMAKE_CXX_FLAGS "-fexceptions -frtti -std=c++11 -DCPU_ONLY")
```

**Comment by abbeyant** [comment]
the jni build result is on below. two positions reported. how can i fix this issue?  @sh1r0 

[armeabi-v7a] Install        : libcaffe.so => libs/armeabi-v7a/libcaffe.so
[armeabi-v7a] Compile++ thumb: caffe_jni <= caffe_jni.cpp
In file included from jni/../android_lib/protobuf/include/google/protobuf/stubs/port.h:62:0,
                 from jni/../android_lib/protobuf/include/google/protobuf/stubs/common.h:40,
                 from jni/../android_lib/caffe/include/caffe/proto/caffe.pb.h:9,
                 from jni/../android_lib/caffe/include/caffe/blob.hpp:9,
                 from jni/../android_lib/caffe/include/caffe/caffe.hpp:7,
                 from jni/caffe_jni.cpp:13:
F:/android-ndk-r10e/platforms/android-21/arch-arm/usr/include/sys/param.h:45:0: warning: "MIN" redefined
 #define MIN(a,b) (((a)<(b))?(a):(b))
 ^
In file included from jni/../android_lib/opencv/sdk/native/jni/include/opencv2/core.hpp:52:0,
                 from jni/../android_lib/opencv/sdk/native/jni/include/opencv2/core/core.hpp:48,
                 from jni/caffe_jni.cpp:9:
jni/../android_lib/opencv/sdk/native/jni/include/opencv2/core/cvdef.h:443:0: note: this is the location of the previous definition
 #  define MIN(a,b)  ((a) > (b) ? (b) : (a))
 ^
In file included from jni/../android_lib/protobuf/include/google/protobuf/stubs/port.h:62:0,
                 from jni/../android_lib/protobuf/include/google/protobuf/stubs/common.h:40,
                 from jni/../android_lib/caffe/include/caffe/proto/caffe.pb.h:9,
                 from jni/../android_lib/caffe/include/caffe/blob.hpp:9,
                 from jni/../android_lib/caffe/include/caffe/caffe.hpp:7,
                 from jni/caffe_jni.cpp:13:
F:/android-ndk-r10e/platforms/android-21/arch-arm/usr/include/sys/param.h:46:0: warning: "MAX" redefined
 #define MAX(a,b) (((a)>(b))?(a):(b))
 ^
In file included from jni/../android_lib/opencv/sdk/native/jni/include/opencv2/core.hpp:52:0,
                 from jni/../android_lib/opencv/sdk/native/jni/include/opencv2/core/core.hpp:48,
                 from jni/caffe_jni.cpp:9:
jni/../android_lib/opencv/sdk/native/jni/include/opencv2/core/cvdef.h:447:0: note: this is the location of the previous definition
 #  define MAX(a,b)  ((a) < (b) ? (b) : (a))
 ^
[armeabi-v7a] Compile++ thumb: caffe_jni <= caffe_mobile.cpp
[armeabi-v7a] SharedLibrary  : libcaffe_jni.so
jni/caffe_jni.cpp:65: error: undefined reference to 'openblas_set_num_threads'
jni/caffe_mobile.cpp:64: error: undefined reference to 'caffe::Net<float>::Net(std::string const&, caffe::Phase, int, std::vector<std::string, std::allocator<std::string> > const*, caffe::Net<float> const*)'
collect2.exe: error: ld returned 1 exit status
make.exe: *** [obj/local/armeabi-v7a/libcaffe_jni.so] Error 1

10:24:33 Build Finished (took 12s.73ms)

**Comment by sh1r0** [comment]
@abbeyant How did you build libcaffe.so?

**Comment by abbeyant** [comment]
@sh1r0 from your shared project caffe-android-lib
https://github.com/sh1r0/caffe-android-lib

**Comment by sh1r0** [comment]
@abbeyant Hmm... What's your setup and steps?

**Comment by abbeyant** [comment]
I was using eclipse and your .mk scripts, not working, then I switched to linux scripts.

**Comment by sh1r0** [comment]
@abbeyant Target ABI? ndk version? cmake version? OS? Build via `build.sh`?

**Comment by abbeyant** [comment]
@sh1r0 firstly i want to create eclipse jni project to build this caffe lib,  'android.mk' and 'application.mk' config is the same as your comments at time "sh1r0 commented on 14 Jul", but failed.(the error log i sticked on ups).(win7 android-ndk-r10e)  Because the deadline of the project is approaching,  I compiled my code into caffe-android-lib to use NDK build, it seems works well. thanks.
