### ISSUE TITLE
How to run directly in Android Phone？

### ISSUE THREAD

**Issue by StephenLeeUSTC** [sh1r0/caffe-android-lib#52]
Hello , I am a ordinary student in university and a new in Android development. Recently, our team want to run caffe directly in an android demoboard because we want to develop a new hardware to accelerate caffe in mobile phone.

So, would  you please tell me that if i can run caffe test/train in an android demoboard like in a Ubuntu PC?

The develop environment is Firefly-Rk3288 , Android 5.1.1 , Ubuntu 14.04 (64) , Android-Ndk-r12b.

I look forward to your early reply. Thank you very much

**Comment by zazd** [comment]
If in CPU， it easy because it is the same as caffe in  http://caffe.berkeleyvision.org/install_apt.html, the dependencies it should be installed. And then see the main function in mobile.cpp, you will find how to run it in rk3288.
If you want to run in GPU, you should first make sure that your  Firefly-Rk3288 linux can support opencl. Because  Firefly-Rk3288 linux has not opencl support. However, someone can make it possible to support opencl by installing the kernel driver. I also try to do it but failed. So if you can do it, tell me the method.

**Comment by StephenLeeUSTC** [comment]
@zazd Thank you for your reply, but in rk3288, the Operating system is Android 5.1.1.  I  adb push the whole caffe in the android_caffe_lib to /data/ dir in the phone. And then I just use command adb shell and run  ./caffe/build/android/CMakeFiles/caffe_jni.dir/caffe_mobile.cpp.o
The result is sh: ./caffe_mobile.cpp.o: not executable: 32-bit ELF file
If there is anything wrong with my runing method ?
About opencl, in fact we are making Intelligent Processor for CNN. And I have no method to handle it till now.

**Comment by StephenLeeUSTC** [comment]
@zazd Thank you for you reply. But the operating system in my rk3288 is Android 5.1.1
If i should run ./caffe-android-lib/caffe/build/android/CMakeFiles/caffe_jni.dir/caffe_mobile.cpp.o in adb shell after i adb push it into my phone in /data/ directory ?
I can't run it in this way, it says "not executable: 32-bit ELF file". Could you tell me in more detail?

**Comment by zazd** [comment]
caffe_mobile.cpp.o？What do you want to do? This is the intermediate product when you compile the caffe_mobile.cpp. It is produced by linux, right? So it can not be run in android. If you want to run as the application in android, you should use https://github.com/sh1r0/caffe-android-demo.

**Comment by StephenLeeUSTC** [comment]
@zazd In fact, I want to run caffe directly in an android machine because I have to measure our hardware performance. It already can get very good performance in x86 cpu. So, I want to know if i can run caffe train with an arm cpu.

**Comment by zazd** [comment]
Training with an arm cpu？If you want to run in android, you should run the caffe as the apk in android? The way of adb shell and just think it as the PC ... on my opinion, it is impossible（I try to do it but give up）. However, you have rk3288, so just do it in ubuntu. It is little difference with the android in rk3288.

**Comment by StephenLeeUSTC** [comment]
@zazd Well, thank you very much, I am doing this just because my boss ask me to try to run caffe train in Android X. I'm having a hard time with this problem.

@sh1r0 If it possible to run caffe in an android phone just like in a ubuntu PC ? Thanks

**Comment by zazd** [comment]
Ok, Training in the mobile seems crazy. Good luck to you.

**Comment by sh1r0** [comment]
Basically, you could follow the similar steps described in https://github.com/sh1r0/caffe-android-lib/issues/7#issuecomment-97049172. But as @zazd said and IMHO, I would not like to do training on mobile devices.

**Comment by StephenLeeUSTC** [comment]
@sh1r0 Oh, thank you,but 
 "1.toggle the comments in these two lines, then re-build for the executable"
the link of two lines can't be open now...Could you please tell me in more detail again ?

**Comment by sh1r0** [comment]
My point is to show you how to run an executable in android via `adb shell`.
In your case, build everything you need and push it into `/data/local/tmp`, which is a good working directory. Then do whatever you want. That's it.

**Comment by StephenLeeUSTC** [comment]
@sh1r0 well, thank you...Maybe I forget to import in my project...
