### ISSUE TITLE
undefined reference to `openblas_set_num_threads'

### ISSUE THREAD

**Issue by dadaxxxx** [sh1r0/caffe-android-lib#58]
hello,when ndk-buil, it occuts "undefined reference to `openblas_set_num_threads'"

but  it has 
#include "cblas.h"

and the android.mk has seted 

LOCAL_C_INCLUDES :=  \
    $(LOCAL_PATH)/../android_lib/openblas/include \
    $(OPENCV_PATH)/sdk/native/jni/include \
    $(LOCAL_SRC_PATH) \
    $(LOCAL_SRC_PATH)/include/ \
    $(LOCAL_PATH)/../android_lib/caffe/include \
    $(LOCAL_PATH)/../android_lib/boost_1_53_0/include \
    $(LOCAL_PATH)/../android_lib/protobuf/include \
    $(LOCAL_PATH)/../android_lib/gflags/include \
    $(LOCAL_PATH)/../android_lib/glog/include \

do you konw why?

**Comment by sh1r0** [comment]
What would like to build? What's your setup? Please provide more information.

**Comment by sh1r0** [comment]
Any further progress?

**Comment by sh1r0** [comment]
Could be reopened if needed.

**Comment by eladyarkoni** [comment]
Any further progress?
