### ISSUE TITLE
Mac Build issues

### ISSUE THREAD

**Issue by tmanthey** [sh1r0/caffe-android-lib#59]
In all build scripts you find:

WD=$(readlink -f "\`dirname $0\`/..")

which does not work on Mac.

WD=\`pwd\`

works fine.

**Comment by sh1r0** [comment]
Hi @tmanthey, I knew the behaviour difference between BSD readlink and GNU readlink, but you could get the later one by `brew install coreutils`. However, `pwd` is not the equivalence.
Thanks.
