### ISSUE TITLE
Why am I unable to clone this repo recursively

### ISSUE THREAD

**Issue by Grillnov** [sh1r0/caffe-android-lib#60]
Terribly sorry about this issue, but I'm still unable to clone submodule caffe.
Git reported unable to checkout the submodule.

**Comment by sh1r0** [comment]
Hi @Grillnov, fixed, please try again.

**Comment by Grillnov** [comment]
Got it, thanks for the reply!

**Comment by Grillnov** [comment]
Thanks for the latest commit.
Well on an unrelated note, your ./build.sh seem to be in conflict with ./scripts/build_openblas.sh. The shell variable ${ANDROID_ABI}'s set as armeabi-v7a with NEON in ./build.sh, whose value is considered not supported in ./scripts/build_openblas.sh.
@sh1r0

**Comment by sh1r0** [comment]
Hi @Grillnov, thanks. It's a mistake, please set `ANDROID_ABI` to one of the supported values: `"armeabi", "armeabi-v7a-hard-softfp with NEON", "arm64-v8a", "x86", and "x86_64"`.

**Comment by Grillnov** [comment]
Okay.
Thanks for the reply. I've successfully built the original version of the code, attempting to make it parallel with OpenCL now.
