### ISSUE TITLE
build.sh ANDROID_ABI

### ISSUE THREAD

**Issue by UndeadBlow** [sh1r0/caffe-android-lib#61]
On line 17 there is:

`export ANDROID_ABI="${ANDROID_ABI:-"armeabi-v7a with NEON"}"
`
But no such option in ./scripts/build_openblas.sh
Maybe It is needed to replace with?

`export ANDROID_ABI="${ANDROID_ABI:-"armeabi-v7a-hard-softfp with NEON"}"`

**Comment by Grillnov** [comment]
[https://github.com/sh1r0/caffe-android-lib/issues/60](#60)
You may want to refer to this issue for some help.
@UndeadBlow

**Comment by sh1r0** [comment]
Please refer to the updated README.
