### ISSUE TITLE
Installing OpenBLAS fails on fresh clone.

### ISSUE THREAD

**Issue by JosiahKane** [sh1r0/caffe-android-lib#65]
Building a completely fresh recursive clone on Ubuntu 16.04 VM with CMake 3.5.1, and, having noticed that you updated, android-ndk-r11c. 

The build seems to work, but the install fails, unable to stat libopenblas_armv8-r0.2.18.a (which, sure enough, doesn't exist: The closest looking thing is libopenblas_armv8p-r0.2.18.a )

**Comment by sh1r0** [comment]
Hi @JosiahKane, there should be a soft link `libopenblas.a` which points to `libopenblas_armv8p-r0.2.18.a`. And, in my case, cmake uses the former one instead of the latter one.

**Comment by xianyi** [comment]
Yes, please use libopenblas.a for the link.

**Comment by JosiahKane** [comment]
There is indeed a soft link to libopenblas_arm8p-r0.2.18.a
That doesn't prevent the error, however, even on a fresh ubuntu install. (The only changes to the ubuntu default are git and the VirtualBox guest additions.)

It can be built by adding another soft link between make and make install from libopenblas_arm8-r0.2.18.a to  libopenblas_arm8p-r0.2.18.a but obviously this isn't an appropriate patch.

**Comment by sh1r0** [comment]
I guess the problem was caused by cmake. I would recommend you to try another version of it.
