### ISSUE TITLE
build opencv error

### ISSUE THREAD

**Issue by blueardour** [sh1r0/caffe-android-lib#67]
hi, @sh1r0 

I have successfully built the gflags glog lmdb libraries. However, when build the opencv, it gave:
[ 92%] Generating src/org/opencv/core/Rect.java
[ 92%] Generating src/org/opencv/core/DMatch.java
[ 92%] Generating src/org/opencv/core/TermCriteria.java
[ 92%] Generating src/org/opencv/core/MatOfDMatch.java
[ 93%] Generating src/org/opencv/core/Point.java
[ 93%] Generating src/org/opencv/core/MatOfPoint3f.java
[ 93%] Generating src/org/opencv/core/Range.java
[ 93%] Generating src/org/opencv/core/RotatedRect.java
[ 93%] Generating src/org/opencv/core/MatOfPoint.java
[ 93%] Generating src/org/opencv/imgproc/Moments.java
[ 93%] Generating src/org/opencv/engine/OpenCVEngineInterface.aidl
[ 93%] Generating OpenCV Android library project. SDK target: lib_target_sdk_target-NOTFOUND
make[2]: *** [build.xml] Error 1
make[1]: *** [modules/java/CMakeFiles/opencv_java.dir/all] Error 2
make: *** [all] Error 2

I searched the google, it seemed a android sdk problem, but I am not very sure.
Fortunately, one could work it around by downloading the prebuilt binary from opencv.org [http://sourceforge.net/projects/opencvlibrary/files/opencv-android/3.1.0/OpenCV-3.1.0-android-sdk.zip/download](url)
and extracted in the android_lib/opencv folder.

Even though my problem is solved, do you have any sense what caused the OpenCV build failed?

**Comment by sh1r0** [comment]
Hi @blueardour,
First, I think your build environment is messed up.
Second, there is no need to generate opencv java libs.
Lastly, FYI, my config is quoted as follows:
```cmake
-- General configuration for OpenCV 3.1.0 =====================================
--   Version control:               3.1.0
-- 
--   Platform:
--     Host:                        Linux 4.2.0-42-generic x86_64
--     Target:                      Android 1 aarch64
--     CMake:                       3.5.2
--     CMake generator:             Unix Makefiles
--     CMake build tool:            /usr/bin/make
--     Configuration:               Release
--   ...
--   Android: 
--     Android ABI:                 arm64-v8a
--     STL type:                    gnustl_static
--     Native API level:            android-21
--     SDK target:                  android_sdk_target_status-NOTFOUND
--     Android NDK:                 /opt/android-ndk-r11c (toolchain: aarch64-linux-android-4.9)
--     android tool:                NO
--     Google Play manager:         NO
--     Android examples:            NO
```

**Comment by sh1r0** [comment]
Should be closed if no further problems.

**Comment by blueardour** [comment]
@sh1r0 
Hi, I check my computer and find the configuration is the same with yours.
'
-- Performing Test HAVE_CXX_WNO_EXTRA
-- Performing Test HAVE_CXX_WNO_EXTRA - Success
-- Performing Test HAVE_CXX_WNO_DEPRECATED_DECLARATIONS
-- Performing Test HAVE_CXX_WNO_DEPRECATED_DECLARATIONS - Success
-- Found PythonInterp: /usr/bin/python2.7 (found suitable version "2.7.3", minimum required is "2.7")
-- Could NOT find PythonInterp: Found unsuitable version "3.2.3", but required is at least "3.4" (found /usr/local/bin/python3)
-- Found PythonInterp: /usr/local/bin/python3 (found suitable version "3.2.3", minimum required is "3.2")
-- Found apache ant 1.8.2: /usr/bin/ant
-- Found android tool: /workspace/soft/android-sdk-linux/tools/android
-- Assume that non-module dependency is available: z (for module opencv_core)
--
-- General configuration for OpenCV 3.1.0 =====================================
--   Version control:               3.1.0
--
--   Platform:
--     Host:                        Linux 3.5.0-23-generic x86_64
--     Target:                      Android 1 aarch64
--     CMake:                       3.5.2
--     CMake generator:             Unix Makefiles
--     CMake build tool:            /usr/bin/make
--     Configuration:               Release
--   Android:
--     Android ABI:                 arm64-v8a
--     STL type:                    gnustl_static
--     Native API level:            android-21
--     SDK target:                  android_sdk_target_status-NOTFOUND
--     Android NDK:                 /opt/android-ndk-r10d (toolchain: aarch64-linux-android-4.9)
--     android tool:                NO
--     Google Play manager:         NO
--     Android examples:            NO
--
--   GUI:
--     GTK+:                        NO
--     GThread :                    NO
--     GtkGlExt:                    NO
--     OpenGL support:              NO
--     VTK support:                 NO
--
--   Media I/O:
--     ZLib:                        z (ver 1.2.3)
--     JPEG:                        build (ver 90)
--     WEBP:                        build (ver 0.3.1)
--     PNG:                         build (ver 1.6.19)
--     TIFF:                        build (ver 42 - 4.0.2)
--     JPEG 2000:                   build (ver 1.900.1)
--     OpenEXR:                     build (ver 1.7.1)
--     GDAL:                        NO
--
--   Video I/O:
--
--   Parallel framework:            pthreads
--
--   Other third-party libraries:
--     Use IPP:                     NO
--     Use Eigen:                   NO
--     Use Cuda:                    NO
--     Use OpenCL:                  NO
--     Use custom HAL:              NO
--
--   Python 2:
--     Interpreter:                 /usr/bin/python2.7 (ver 2.7.3)
--
--   Python 3:
--     Interpreter:                 /usr/local/bin/python3 (ver 3.2.3)
--
--   Python (for build):            /usr/bin/python2.7
--
--   Java:
--     ant:                         /usr/bin/ant (ver 1.8.2)
--     Java wrappers:               YES
--     Java tests:                  NO
--
--   Matlab:                        NO
--
--   Tests and samples:
--     Tests:                       NO
--     Performance tests:           NO
--     C/C++ Examples:              NO
'

As you mention, the java wrapper is not necessary, so I add the following to the cmake cmdline.

 -DBUILD_FAT_JAVA_LIB=OFF \
 -DHAVE_opencv_java=NO \

to avoid the Java lib, and now not error for building. sigh~

**Comment by blueardour** [comment]
By the way, when building the OpenBLAS, it gave many redifined warnings:
`/workspace/soft/android-ndk-r10d/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/bin/aarch64-linux-android-gcc --sysroot=/workspace/soft/android-ndk-r10d/platforms/android-21/arch-arm64 -c --sysroot=/workspace/soft/android-ndk-r10d/platforms/android-21/arch-arm64 -O2 -DMAX_STACK_ALLOC=2048 -fopenmp -Wall -DF_INTERFACE_GFORT -fPIC -DNO_LAPACK -DNO_LAPACKE -DSMP_SERVER -DUSE_OPENMP -DNO_WARMUP -DMAX_CPU_NUMBER=8 -march=armv8-a -DASMNAME= -DASMFNAME=_ -DNAME=_ -DCNAME= -DCHAR_NAME=\"_\" -DCHAR_CNAME=\"\" -DNO_AFFINITY -I. -O2 -DMAX_STACK_ALLOC=2048 -fopenmp -Wall -DF_INTERFACE_GFORT -fPIC -DNO_LAPACK -DNO_LAPACKE -DSMP_SERVER -DUSE_OPENMP -DNO_WARMUP -DMAX_CPU_NUMBER=8 -march=armv8-a -DASMNAME=scabs1 -DASMFNAME=scabs1_ -DNAME=scabs1_ -DCNAME=scabs1 -DCHAR_NAME=\"scabs1_\" -DCHAR_CNAME=\"scabs1\" -DNO_AFFINITY -I.. -DCOMPLEX -UDOUBLE -DF_INTERFACE ../kernel/arm64/../generic/cabs.c -o scabs1.o
/workspace/soft/android-ndk-r10d/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/bin/aarch64-linux-android-gcc --sysroot=/workspace/soft/android-ndk-r10d/platforms/android-21/arch-arm64 -c --sysroot=/workspace/soft/android-ndk-r10d/platforms/android-21/arch-arm64 -O2 -DMAX_STACK_ALLOC=2048 -fopenmp -Wall -DF_INTERFACE_GFORT -fPIC -DNO_LAPACK -DNO_LAPACKE -DSMP_SERVER -DUSE_OPENMP -DNO_WARMUP -DMAX_CPU_NUMBER=8 -march=armv8-a -DASMNAME= -DASMFNAME=_ -DNAME=_ -DCNAME= -DCHAR_NAME=\"_\" -DCHAR_CNAME=\"\" -DNO_AFFINITY -I. -O2 -DMAX_STACK_ALLOC=2048 -fopenmp -Wall -DF_INTERFACE_GFORT -fPIC -DNO_LAPACK -DNO_LAPACKE -DSMP_SERVER -DUSE_OPENMP -DNO_WARMUP -DMAX_CPU_NUMBER=8 -march=armv8-a -DASMNAME=dcabs1 -DASMFNAME=dcabs1_ -DNAME=dcabs1_ -DCNAME=dcabs1 -DCHAR_NAME=\"dcabs1_\" -DCHAR_CNAME=\"dcabs1\" -DNO_AFFINITY -I.. -DCOMPLEX -DDOUBLE -DF_INTERFACE ../kernel/arm64/../generic/cabs.c -o dcabs1.o
<command-line>:0:0: warning: "ASMNAME" redefined
<command-line>:0:0: note: this is the location of the previous definition
<command-line>:0:0: warning: "ASMFNAME" redefined
<command-line>:0:0: note: this is the location of the previous definition
<command-line>:0:0: warning: "NAME" redefined
<command-line>:0:0: note: this is the location of the previous definition
<command-line>:0:0: warning: "CNAME" redefined
<command-line>:0:0: note: this is the location of the previous definition
<command-line>:0:0: warning: "CHAR_NAME" redefined
<command-line>:0:0: note: this is the location of the previous definition
<command-line>:0:0: warning: "CHAR_CNAME" redefined
<command-line>:0:0: note: this is the location of the previous definition
<command-line>:0:0: warning: "ASMNAME" redefined
<command-line>:0:0: note: this is the location of the previous definition
<command-line>:0:0: warning: "ASMFNAME" redefined
<command-line>:0:0: note: this is the location of the previous definition
<command-line>:0:0: warning: "NAME" redefined
<command-line>:0:0: note: this is the location of the previous definition
<command-line>:0:0: warning: "CNAME" redefined
<command-line>:0:0: note: this is the location of the previous definition
<command-line>:0:0: warning: "CHAR_NAME" redefined
<command-line>:0:0: note: this is the location of the previous definition
<command-line>:0:0: warning: "CHAR_CNAME" redefined
<command-line>:0:0: note: this is the location of the previous definition
<command-line>:0:0: warning: "ASMNAME" redefined
<command-line>:0:0: note: this is the location of the previous definition
<command-line>:0:0: warning: "ASMFNAME" redefined
<command-line>:0:0: note: this is the location of the previous definition
<command-line>:0:0: warning: "NAME" redefined
<command-line>:0:0: note: this is the location of the previous definition
<command-line>:0:0: warning: "CNAME" redefined
<command-line>:0:0: note: this is the location of the previous definition
<command-line>:0:0: warning: "CHAR_NAME" redefined
<command-line>:0:0: note: this is the location of the previous definition
<command-line>:0:0: warning: "CHAR_CNAME" redefined
<command-line>:0:0: note: this is the location of the previous definition`

All build process runs OK. But I worry whether the warning would cause some unexpected behaviors.

**Comment by sh1r0** [comment]
Hi @blueardour,

1. I noticed that you got both `-- Found android tool: /workspace/soft/android-sdk-linux/tools/android` and `-- Found apache ant 1.8.2: /usr/bin/ant` in your cmake config and thus  
    ```
    -- Java:  
    -- ant: /usr/bin/ant (ver 1.8.2)  
    -- Java wrappers: YES  
    ```  

2. I found that you got repeated `--sysroot` flag in your `$CC` and I'm afraid that your environment variables are messed up. FYI, I list my  openblas build config below.
    ```
  OS               ... Android
  Architecture     ... arm64
  BINARY           ... 64bit
  C compiler       ... GCC  (command line : /opt/android-ndk-r11c/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/bin/aarch64-linux-android-gcc --sysroot=/opt/android-ndk-r11c/platforms/android-21/arch-arm64)
  Fortran compiler ... GFORTRAN  (command line : /opt/android-ndk-r11c/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/bin/aarch64-linux-android-gfortran --sysroot=/opt/android-ndk-r11c/platforms/android-21/arch-arm64)
  Library Name     ... libopenblas_armv8p-r0.2.18.a (Multi threaded; Max num-threads is 8)
    ```

**Comment by blueardour** [comment]
@sh1r0   Hi,thanks for you comment. It is very helpful. (No further questions, so shall we close it?)

**Comment by hpsaturn** [comment]
I had the same issue, but I fixed it changing the android-sdk tools like this thread:
https://github.com/liballeg/allegro5/issues/743
