### ISSUE TITLE
Boost compilation fails with `armeabi-v7a-hard-softfp with NEON` and NDK12b

### ISSUE THREAD

**Issue by jainanshul** [sh1r0/caffe-android-lib#68]
I get the following error while compiling boost running the command `ANDROID_ABI="armeabi-v7a-hard-softfp with NEON" ./build.sh android-ndk-r12b`

```
sources/cxx-stl/gnu-libstdc++/4.9/include/cstddef:44:28: fatal error: bits/c++config.h: No such file or directory
 #include <bits/c++config.h>
```

boost compiles fine with default ANDROID_ABI.

**Comment by jainanshul** [comment]
Tested with NSK11c and boost is compiling fine with `armeabi-v7a-hard-softfp with NEON` as well.

**Comment by filipetrocadoferreira** [comment]
I'm facing the same problem. Downgrading NDK is the only workaround?

**Comment by sh1r0** [comment]
https://github.com/sh1r0/caffe-android-lib/issues/57#issuecomment-255511524
