### ISSUE TITLE
for faster-rcnn:fail to parse net parameters file

### ISSUE THREAD

**Issue by at9404** [sh1r0/caffe-android-lib#69]
I added proposallayer ,roipoolinglayer to this lib and run faster rcnn in android device,but it can't parse the faster_rcnn_test.pt.
error log is:Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter file
Caffe-Android-demo  parse the deploy.prototxt well  
what is the diffrence between .prototxt and .pt ,and how to fix it.
please help me!

**Comment by sh1r0** [comment]
Hi @at9404, 
What's your implementation based on? [https://github.com/rbgirshick/py-faster-rcnn](https://github.com/rbgirshick/py-faster-rcnn)? Please provide more details, thanks.

**Comment by at9404** [comment]
@sh1r0 yes I changed  py-faster-rcnn to a C++ style and I have  solved the problem.because I forgot to add the definition to caffe.proto.thank you!!!
