### ISSUE TITLE
Use "main"

### ISSUE THREAD

**Issue by mtngld** [sh1r0/caffe-android-lib#7]
Hi,

In order to unit test the JNI I would like to compile and run it using the main function, are you able to use it for testing? How can this be done? I also noticed the mobile/main.cpp under caffe, what is the purpose of that testing?

Thanks

**Comment by sh1r0** [comment]
`mobile/main.cpp` is for desktop debugging.
For mobile debugging, please follow the steps below:
1. toggle the comments in these two [lines](https://github.com/sh1r0/caffe-android-lib/blob/master/caffe-mobile/jni/Android.mk#L122-L123), then re-build for the executable.
2. push it into `/data/local/tmp`
3. `chmod 755 /data/local/tmp/<executable>`
4. `export LD_LIBRARY_PATH=<lib path>:$LD_LIBRARY_PATH`
5. run...
