### ISSUE TITLE
Error:(13) undefined reference to 'caffe::Net<float>::Net(std::string const&, caffe::Phase, int, std::vector<std::string, std::allocator<std::string> > const*, caffe::Net<float> const*)'

### ISSUE THREAD

**Issue by ameld** [sh1r0/caffe-android-lib#71]
Hi i need a bit help because i can't figure out what the problem is.

I have started an Android Project using gradle-experimental:0.7.3 for NDK  and linking.
Everything seams to work fine and it compiles except one line of code:

```
std::string model_file;
caffe::Net<float> net(model_file, caffe::Phase::TEST, 0, NULL, NULL);
```

i get the Error:(13) undefined reference to 'caffe::Net<float>::Net(std::string const&, caffe::Phase, int, std::vector<std::string, std::allocator<std::string> > const_, caffe::Net<float> const_)'

I was thinking this was due to bad linking but the second Constructor:

```
caffe::NetParameter param;
caffe::Net<float> net(param, NULL);
```

works just fine.

I would be grateful if anyone can give me a hint or clue what the problem may be,
thanks in advance

**Comment by sh1r0** [comment]
Hi @ameld, if you would like to build external libs based on libcaffe, you should not strip it (see [this](https://github.com/sh1r0/caffe-android-lib/blob/master/scripts/build_caffe.sh#L60)).

**Comment by sh1r0** [comment]
Any further progress?

**Comment by ameld** [comment]
Sorry, the last past days i was studying so i didn't do much.
I tried without striping but still get the Error "undefined reference" for these 2 Lines 
```
net_.reset(new Net<float>(model_file, TEST));
net_->CopyTrainedLayersFrom(trained_file);
```

Here is the Android Project [https://github.com/ameld/CaffeTesting](url) maybe someone can see my mistake or tell my what I'm doing wrong. Either way i would be thankful and also to mention my Android skills are pretty bad.

**Comment by sh1r0** [comment]
Hi @ameld,

I'm not familiar with build ndk project via gradle. But, I succeeded in building your project (`CaffeClassification.h` & `CaffeClassification.cpp`) by using conventional ndk-build way with `Android.mk` shown below.

```makefile
LOCAL_PATH := $(call my-dir)

# C++ full library
# =======================================================
include $(CLEAR_VARS)
LOCAL_MODULE    := caffe
LOCAL_SRC_FILES := $(NDK_PROJECT_PATH)/../android_lib/caffe/lib/libcaffe.so
include $(PREBUILT_SHARED_LIBRARY)

#-----------------------------------------------------------------------------
include $(CLEAR_VARS)
LOCAL_MODULE := caffe_classification

LOCAL_SRC_FILES  := $(LOCAL_PATH)/CaffeClassification.cpp
LOCAL_C_INCLUDES := $(LOCAL_PATH) \
                    $(NDK_PROJECT_PATH)/../android_lib/caffe/include \
                    $(NDK_PROJECT_PATH)/../android_lib/boost/include \
                    $(NDK_PROJECT_PATH)/../android_lib/gflags/include \
                    $(NDK_PROJECT_PATH)/../android_lib/glog/include \
                    $(NDK_PROJECT_PATH)/../android_lib/protobuf/include \
                    $(NDK_PROJECT_PATH)/../android_lib/openblas/include \
                    $(NDK_PROJECT_PATH)/../android_lib/opencv/sdk/native/jni/include

LOCAL_SHARED_LIBRARIES := caffe
LOCAL_LDLIBS           := -lm -llog
LOCAL_CPPFLAGS         += -fexceptions -frtti -std=c++11 -DCPU_ONLY

include $(BUILD_SHARED_LIBRARY)
```

**Comment by ameld** [comment]
I started a new project and now its compiling for me also, but I still don't know what the issue was.
The new project is identical to the first except now I'm using gradle-experimental:0.8.1 instead of 0.7.3 maybe that solve id.

But now I'm facing a new problem while executing the CaffeClassification constructor,  i don't get any Errors or Warnings the App just closes on this line `net_->CopyTrainedLayersFrom(trainer_file);`

**Comment by sh1r0** [comment]
Probably caused by out of memory I guess.

**Comment by sh1r0** [comment]
@ameld Any updates?
