### ISSUE TITLE
Failed to build OpenBLAS when trying to build caffe-android-lib

### ISSUE THREAD

**Issue by vikasmarath** [sh1r0/caffe-android-lib#72]
I get the below error

C Compiler (/root/vikas/android-ndk-r11c/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/bin/aarch64-linux-android-gcc --sysroot=/root/vikas/android-ndk-r11c/platforms/android-21/arch-arm64) is something wrong.
1 at ./c_check line 24.
make: *** [config.h] Error 13
Makefile.system:165: Makefile.conf: No such file or directory
Makefile.system:906: Makefile.: No such file or directory
make: *** No rule to make target 'Makefile.'.  Stop.

**Comment by sh1r0** [comment]
@vikasmarath Could you provide more details? Did you use build_openblas.sh?

**Comment by omga** [comment]
I actually had the same error when tried to build from linux and pointed to ndk for windows. After I pointed to ndk for linux it successfully built libopenblas_armv8p-r0.2.18.a

But I'm not sure what are the next steps to include this library in my android project. In caffee demo app I see there are .so files in jniLibs folder. Should I generate so files somehow or just add .a files?
@sh1r0 Can you please help me?

**Comment by sh1r0** [comment]
@omga
First, you should use not ndk for windows on linux, as it's a cross-compilation toolchain for android where host machine is windows.
Second, what's your purpose? Would you like to use libopenblas solely? If so, you should ask the usage problem in https://github.com/xianyi/OpenBLAS.
Thanks.

**Comment by sh1r0** [comment]
Could be reopened if needed.

**Comment by ten23** [comment]
I get the same error.
Could you give me a solutioin for this error ?

**Comment by sh1r0** [comment]
@ten23 Details?

**Comment by DVEfremov** [comment]
I've got just the same error 
Step to reproduce 
```
$ git clone https://github.com/sh1r0/caffe-android-lib
$ export NDK_ROOT=/home/user/Soft/android-ndk-r12b
$ export ANDROID_ABI="x86_64"
$ ./build.sh
make: *** No rule to make target 'clean'.  Stop.
Failed to build OpenBLAS
```

**Comment by sh1r0** [comment]
@DVEfremov Please refer to [README](https://github.com/sh1r0/caffe-android-lib/blob/master/README.md#build), you should either clone all submodules recursively or use `git submodule update` to get all submodules up-to-date. Thanks.

**Comment by DVEfremov** [comment]
Sorry I forgot to clone recursively  all sub modules ...
