### ISSUE TITLE
undefined reference to GOMP_parallel

### ISSUE THREAD

**Issue by Stark123** [sh1r0/caffe-android-lib#73]
_Hi I am getting this error while building openBLAS-_

make[1]: *** [sblat2] Error 1
../libopenblas_armv8p-r0.2.20.dev.a(zaxpy.o): In function `zaxpy_':
zaxpy.c:(.text+0x94): undefined reference to `omp_in_parallel'
zaxpy.c:(.text+0xfc): undefined reference to `omp_get_max_threads'
../libopenblas_armv8p-r0.2.20.dev.a(zswap.o): In function `zswap_':
zswap.c:(.text+0x60): undefined reference to `omp_in_parallel'
zswap.c:(.text+0xe0): undefined reference to `omp_get_max_threads'
../libopenblas_armv8p-r0.2.20.dev.a(zscal.o): In function `zscal_':
zscal.c:(.text+0x68): undefined reference to `omp_in_parallel'
zscal.c:(.text+0xc0): undefined reference to `omp_get_max_threads'
../libopenblas_armv8p-r0.2.20.dev.a(zdscal.o): In function `zdscal_':
zscal.c:(.text+0x68): undefined reference to `omp_in_parallel'
zscal.c:(.text+0xb8): undefined reference to `omp_get_max_threads'
../libopenblas_armv8p-r0.2.20.dev.a(blas_server.o): In function `exec_blas._omp_fn.0':
blas_server_omp.c:(.text+0x20): undefined reference to `omp_get_num_threads'
blas_server_omp.c:(.text+0x28): undefined reference to `omp_get_thread_num'
blas_server_omp.c:(.text+0x168): undefined reference to `omp_get_thread_num'
../libopenblas_armv8p-r0.2.20.dev.a(blas_server.o): In function `goto_set_num_threads':
blas_server_omp.c:(.text+0x2d0): undefined reference to `omp_set_num_threads'
../libopenblas_armv8p-r0.2.20.dev.a(blas_server.o): In function `exec_blas':
blas_server_omp.c:(.text+0x678): undefined reference to `GOMP_parallel'
collect2: error: ld returned 1 exit status
make[1]: *** [zblat1] Error 1
make[1]: Leaving directory `/home/gaurav/deeplearning/caffe-android-lib/OpenBLAS/test'
make: *** [tests] Error 2
Failed to build OpenBLAS

_Any suggestions?_

**Comment by sh1r0** [comment]
In this project, we use OpenBLAS v2.0.18.

**Comment by Stark123** [comment]
Thanks.
I am building the same OpenBLAS v0.2.18 as given by caffe-android-lib project. But while making it generates this libopenblas_armv8p-r0.2.20.dev.a file. 
I couldn't figure out where I am getting wrong here.

**Comment by sh1r0** [comment]
Then I think you should create an issue in https://github.com/xianyi/OpenBLAS instead of here.
Thanks.

**Comment by Stark123** [comment]
Thanks.
