### ISSUE TITLE
Failed to build OpenBLAS when trying to build caffe-android-lib 2

### ISSUE THREAD

**Issue by ten23** [sh1r0/caffe-android-lib#77]
I get the below error.
I think this error is same as #72 issue.

Could you give me a solutioin for this error ?
---

C Compiler (/home/caffe-android-lib/homedevelopandroid-ndk-r10e/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/bin/aarch64-linux-android-gcc --sysroot=/home/caffe_lib/caffe-android-lib/homedevelopandroid-ndk-r10e/platforms/android-21/arch-arm64) is something wrong.
1 at ./c_check line 24.
make: **\* [config.h] error 2
Makefile.system:166: Makefile.conf: No such file or directory
Makefile.system:909: Makefile.: No such file of directory
make: **\* No rule to make target `Makefile.' stop.
## Failed to build OpenBLAS

If NDK version changes from r10e to r11c, result is same too (same error occur).

**Comment by sh1r0** [comment]
In #72, the issue was casued by using incorrect ndk, and I have no idea how to reproduce yours. Could you provide more details about your environment?

**Comment by sh1r0** [comment]
I noticed that your c compiler path was strange.
* `/home/caffe-android-lib/homedevelopandroid-ndk-r10e/`toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/bin/aarch64-linux-android-gcc
* `/home/caffe_lib/caffe-android-lib/homedevelopandroid-ndk-r10e/`platforms/android-21/arch-arm64

Did you notice that difference?

**Comment by ten23** [comment]
Sorry, this information is wrong.
Correct is the following error message.

C Compiler (/home/caffe_lib/caffe-android-lib/homedevelopandroid-ndk-r10e/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/bin/aarch64-linux-android-gcc --sysroot=/home/caffe_lib/caffe-android-lib/homedevelopandroid-ndk-r10e/platforms/android-21/arch-arm64) is something wrong.

**Comment by ten23** [comment]
> Could you provide more details about your environment?

What environment information should I share ?

**Comment by sh1r0** [comment]
For example, what's your OS? how did you build openblas? how to reproduce this issue?
Thanks.

**Comment by ten23** [comment]
Could you confirm the following ?

<environment>
Ubuntu 14.04
android-ndk-r13 .. etc
cmake version 3.5.2

<command>
$ git clone --recursive https://github.com/sh1r0/caffe-android-lib.git
$ cd caffe-android-lib
$ export ANDROID_ABI="arm64-v8a"
$ ./build.sh <ndk path>

**Comment by sh1r0** [comment]
Hi @ten23, I've confirmed that I did not have any issues.

**Comment by smudge1307** [comment]
I use android-ndk-r10d,cmake-3.3.2 on ubuntu 1404 64bit .it took effect ,but there is other issue,when build OpenBLAS,it shows that Copying the static library to /opt/caffe-android-lib/android_lib/openblas/lib
【install: 无法获取"libopenblas_armv7p-r0.2.18.a" 的文件状态(stat): 没有那个文件或目录(means that nu such files)】

**Comment by sh1r0** [comment]
@ten23 Any updates?

**Comment by sh1r0** [comment]
Could be reopened if needed.
