### ISSUE TITLE
Error while run ./build.sh

### ISSUE THREAD

**Issue by smudge1307** [sh1r0/caffe-android-lib#78]
Hi,hum I have something wrong while run ./build.sh .
I use Ubuntu 1404 64bit,android_ndk_r10d_linux_x86_64
./build.sh is runned,but when build the OpenBLAS,there is an error shows that 【Copying the static library to /opt/caffe-android-lib/android_lib/openblas/lib
install: 无法获取"libopenblas_armv7p-r0.2.18.a" 的文件状态(stat): 没有那个文件或目录(means that nu such files)】
then I cd ./OpenBLAS there is libopenblas_armv7-r0.2.18.a but no libopenblas_armv7p-r0.2.18.a.
where thr wrong is ? Would you please help me? Thank you very much .

**Comment by sh1r0** [comment]
Since libopenblas_armv7p-r0.2.18.a is the right one, you should upgrade your ndk or cmake.

**Comment by smudge1307** [comment]
@sh1r0  Appreciate for your answer! I'll have a try.

**Comment by sh1r0** [comment]
Any updates? Or, this should be closed.

**Comment by smudge1307** [comment]
No,thank you.
I download OpenBlas0.2.18 individually and then run the build_caffe.sh,and succeed.
But I have one more question,how to use pycaffe on android? I used Qpython.

**Comment by sh1r0** [comment]
Sorry, there's no plan to support pycaffe. But if you make it, PRs are welcome, thanks.
