### ISSUE TITLE
Project generate DYN files but not EXEC files

### ISSUE THREAD

**Issue by extraaaaa** [sh1r0/caffe-android-lib#79]
i have built caffe-android-lib successfully using "Android-ABI = armeabi" ,and then i want to test caffe on a arm core ,linux machine . i test files include "android_lib/caffe/bin/caffe" and "android_lib/caffe/bin/classification",(the needed *.so have copied to the target machine ),but it didn't work.
I use tool "arm-linux-readelf"to read the files("caffe, classification") and i found that file type are"DYN(Shared
object file)",but not EXEC(Executable file). I want to know how to config the project to generate EXEC files ，thank you！

**Comment by sh1r0** [comment]
It's normally DYN as a result of PIE (http://stackoverflow.com/questions/30555248/readelf-reports-program-is-a-shared-library-instead-of-executable). Are you sure that your target machine is android-compatible?

**Comment by extraaaaa** [comment]
target machine is not android ，but linux and arm. because caffe don't support arm so i found caffe-android-lib（it supports arm and android is based on linux），do you mean it can only be used in an android machine？

**Comment by sh1r0** [comment]
Basically, it's built with android-ndk, and I doubt that it support generic arm-based devices.
