### ISSUE TITLE
Error running ./build.sh

### ISSUE THREAD

**Issue by dpr10** [sh1r0/caffe-android-lib#80]
Hi, I have problems running ./build.sh.
I use Debian 8 64 bit and android_ndk_r13_x86_x64.
./build.sh is running but when build OpenBLAS in the install process show the following error:
``
/bin/sh: 1: Syntax error: "(" unexpected
Makefile.install:23: recipe for target 'install' failed
make[1]: [install] Error 2 (ignored)
/bin/sh: 1: Syntax error: "(" unexpected
Makefile.install:23: recipe for target 'install' failed
make[1]: [install] Error 2 (ignored)
/bin/sh: 1: Syntax error: "(" unexpected
Makefile.install:23: recipe for target 'install' failed
make[1]: [install] Error 2 (ignored)
/bin/sh: 1: Syntax error: "(" unexpected
Makefile.install:23: recipe for target 'install' failed
make[1]: [install] Error 2 (ignored)
/bin/sh: 1: Syntax error: "(" unexpected
Makefile.install:23: recipe for target 'install' failed
make[1]: [install] Error 2 (ignored)
/bin/sh: 1: Syntax error: "(" unexpected
Makefile.install:23: recipe for target 'install' failed
make[1]: *** [install] Error 2
``
I check OpenBLAS/Makefile.install and all looks fine to me. Any ideas? Would you please help me?
Thank you so much?

**Comment by sh1r0** [comment]
What's your target ABI and your cmake version?

**Comment by dpr10** [comment]
This is embarassing. The problem was my cmake. Thanks a lot for the help.

**Comment by z6491679** [comment]
hello， I meet the same problem，can you tell me how to fix it？what‘s the problem with cmake？My cmake verision is 3.5.1
