### ISSUE TITLE
Managed to make it run on GPUs on the phones, with extremely low performance.

### ISSUE THREAD

**Issue by Grillnov** [sh1r0/caffe-android-lib#81]
We managed to make it run on GPUs by replacing the original caffe module with its OpenCL branch, and then integrated it into the caffe-android-demo project.
Android Studio reports that its Adreno GPU is indeed used, with an unacceptable performance though. After this modification it takes much longer to initiate the demo app, and almost 10 times the time needed for detection on CPU.
Any bright ideas lads? I'm still wondering how.

**Comment by sh1r0** [comment]
Please refer to the discussions in #23. In short, the opencl kernels are not designed for mobile chips which lead to bad performance.
