### ISSUE TITLE
build error with opencl_dev

### ISSUE THREAD

**Issue by neil1899** [sh1r0/caffe-android-lib#83]
hi

when i use the branch of opencl_dev, and update the submodule, when i build use
export USE_OPENBLAS=1
export ANDROID_ABI="armeabi-v7a-hard-softfp with NEON"
./build.sh <path/to/ndk>

occurs error:
-- Found OpenCL: /home/niewei/work/DL/Android-Caffe/caffe-android-lib/android_lib/opencl-android/lib/libOpenCL.so  
CMake Error at cmake/Dependencies.cmake:79 (message):
  ViennaCL required for GREENTEA but not found.
Call Stack (most recent call first):
  CMakeLists.txt:75 (include)
-- Configuring incomplete, errors occurred!

could you help me?

thanks in advance!

**Comment by sh1r0** [comment]
@neil1899 You need ViennaCL, and you could get it via [get_viennacl.sh](https://github.com/sh1r0/caffe-android-lib/blob/opencl_dev/scripts/get_viennacl.sh).

**Comment by neil1899** [comment]
hi @sh1r0 

i found a issue: my platform is qualcomm 820, the lib of libOpenCL.so has so many dependences, so i want to use dlopen function to using the libOpenCL.

now, i can build done, but it always shows that:
<command-line>:0:0: note: this is the location of the previous definition
Is it ok?

thanks in advance!

**Comment by sh1r0** [comment]
Sorry, I'm not sure about that. Note that the `opencl_dev` branch as its name suggest is in developing stage and is currently pending due to the performance issue I mentioned before.

**Comment by neil1899** [comment]
hi @sh1r0 

what's the test did you run? when i run the test_net, it Aborted

**Comment by sh1r0** [comment]
@neil1899 Yes, I used that before for testing, but I'm not sure if it still working.

**Comment by sh1r0** [comment]
Could be reopened if needed.
