### ISSUE TITLE
does not support  protobuf 3.0

### ISSUE THREAD

**Issue by perp** [sh1r0/caffe-android-lib#87]
terminate called after throwing an instance of 'google::protobuf::FatalException'
  what():  This program was compiled against version 2.6.1 of the Protocol Buffer runtime library, which is not compatible with the installed version (3.0.0).  Contact the program author for an update.  If you compiled the program yourself, make sure that your headers are from the same version of Protocol Buffers as your link-time library.  (Version verification failed in "out/target/product/max1/gen/SHARED_LIBRARIES/libGLES_trace_intermediates/proto/frameworks/native/opengl/libs/GLES_trace/proto/gltrace.pb.cc".)
Aborted 

This is caused by the version of protobuf.so on android phone is 2.6.1,but I used the newest to compile libcaffe.so, So they doesn't match.
How to build protobuf a new dynamic library for libcaffe.so to link?

**Comment by sh1r0** [comment]
@perp In this project, we do build jni libs and host protoc based on protobuf 3.0. Please check your environment, thanks.

**Comment by perp** [comment]
@sh1r0 Thanks for your reply！
On my phone libprotobuf-cpp-lite.so version is 2.6.1, but protobuf is compiled as an static library into libcaffe.so. So I have no idea why libcaffe.so still finds the older version.

**Comment by sh1r0** [comment]
@perp How did you test the libs?

**Comment by perp** [comment]
A Native exe(contains camera capturing,face detection(dlib) facerecognition(caffe-android)) calling libcaffe.so

**Comment by sh1r0** [comment]
Would you mind to have a try on this [example](https://github.com/BVLC/caffe/tree/master/examples/cpp_classification) first? The binary is built as `classification` in `caffe-android-lib/android_lib/caffe/bin/`.

**Comment by perp** [comment]
It's OK  result is below
an.binaryproto /data/synset_words.txt /data/cat.jpg                           <
---------- Prediction for /data/cat.jpg ----------
0.3134 - "n02123045 tabby, tabby cat"
0.2380 - "n02123159 tiger cat"
0.1235 - "n02124075 Egyptian cat"
0.1003 - "n02119022 red fox, Vulpes vulpes"
0.0715 - "n02127052 lynx, catamount"

**Comment by sh1r0** [comment]
OK, it turns out the issue is not related to libcaffe, then I'm afraid that something is messed up in your setup.

**Comment by perp** [comment]
The actual answer is that
1. libcaffe depends on libprotobuf 3.0
2. android camera and android surface view(gui) depends on libprotobuf2.6.1(the original version in my android phone).
So you could not use android native code to access android camera and surface view while calling libcaffe only if the libprotobuf version is all the same.
