### ISSUE TITLE
how to use caffe.so caffe_jni.so in android Library

### ISSUE THREAD

**Issue by JohnTian** [sh1r0/caffe-android-lib#88]
Thanks for your awesome work on **caffe-android-lib**. 
I created an android library (caffemobile), the structure just like the following picture:

![pic](http://img.my.csdn.net/uploads/201612/09/1481275361_8353.jpg)

But, when i ran the app, it crashed and report 

```
java.lang.UnsatisfiedLinkError: No implementation found for void org.jt.caffemoblie.CaffeMobile.setNumThreads(int) (tried Java_org_jt_caffemoblie_CaffeMobile_setNumThreads and Java_org_jt_caffemoblie_CaffeMobile_setNumThreads__I)
                      at org.jt.caffemoblie.CaffeMobile.setNumThreads(Native Method)
```

Could you help me finger out the reason, please? 
God bless you!
Best regards!

**Comment by csrgxtu** [comment]
the error indicates that the so file you include in your projejct cant be find or located in Java, so to simplify the problem, can u just create a helloworld project and import the so and use it in your java code, see if it works?

**Comment by sh1r0** [comment]
@JohnTian 
Please refer to [CaffeMobile.java](https://github.com/sh1r0/caffe-android-demo/blob/master/app/src/main/java/com/sh1r0/caffe_android_lib/CaffeMobile.java#L1) and [caffe_jni.cpp](https://github.com/sh1r0/caffe/blob/080c2381625f1e2c1bbabd7ab4cc8d8581e3d19e/android/caffe_jni.cpp), you should not change the package name unless you make the corresponding changes and build on your own. Thanks.

**Comment by JohnTian** [comment]
@sh1r0 Thanks! I will check it out soon.
