### ISSUE TITLE
caffe time fails with seg fault at adnroid

### ISSUE THREAD

**Issue by DVEfremov** [sh1r0/caffe-android-lib#89]
I'm trying to use caffe time command for my project 
but it fails with seg fault at adnroid now.
Just may be you or some one else know what wrong. 
Steps to reproduce 
* build caffe-android-lib for  ANDROID_ABI="armeabi" or export ANDROID_ABI="armeabi"
* adb push mkdir /data/local/tmp/caffe
* adb push caffe/build/tools/caffe /data/local/tmp/caffe/caffe
* adb push caffe/build/lib/libcaffe.so /data/local/tmp/caffe/libcaffe.so
* adb push caffe/models/bvlc_alexnet/deploy.prototxt /data/local/tmp/caffe/deploy.prototxt
* adb shell 
* cd /data/local/tmp/caffe
* chmod 777 * 
* export LD_LIBRARY_PATH=/data/local/tmp/caffe:$LD_LIBRARY_PATH
* ./caffe time --model=/data/local/tmp/caffe/deploy.prototxt --iterations=1
And I've got Segmentation fault

**Comment by DVEfremov** [comment]
any advice would be appreciated

**Comment by sh1r0** [comment]
Hi @DVEfremov, it's a known issue (#35).
