### ISSUE TITLE
Mean image 

### ISSUE THREAD

**Issue by tzutalin** [sh1r0/caffe-android-lib#9]
Thanks for provide android mobile sample code. But I have a question about the mean image.
From you source code, you didn't subtract the mean image while predicting. For bvlc_reference_caffenet model, it will subtract the mean image while training. Should you do the same thing while predicting?

**Comment by sh1r0** [comment]
In my case, I use MemoryDataLayer to dynamically [load](https://github.com/sh1r0/caffe-android-lib/blob/master/caffe-mobile/jni/caffe_mobile.cpp#L80-L85) images during runtime. And mean value subtraction is done by [AddDatumVector](https://github.com/BVLC/caffe/blob/master/src/caffe/layers/memory_data_layer.cpp#L44) in MemoryDataLayer. Thus, I do perform mean value subtraction in my prediction flows.

**Comment by tzutalin** [comment]
I see. Thanks very much.
