### ISSUE TITLE
Caffe on windows???

### ISSUE THREAD

**Issue by DushyantMainwal** [sh1r0/caffe-android-lib#91]
Is there a way to make an android project using caffe on windows
using build.sh on bash gives me error.. 
$  ./build.sh D:/Softwares/Sdk/androidsdk/ndk-bundle
./scripts/build_openblas.sh: line 16: [: missing `]'
./scripts/build_openblas.sh: line 17: MINGW64_N: command not found
Unknown OS
Failed to build OpenBLAS

**Comment by sh1r0** [comment]
So far, there's no plan to support Windows. But, you could try to run on unix-like environment like cygwin ,or using vm or docker.

**Comment by DushyantMainwal** [comment]
okay after installing new cygwin(64 bit) on my windows..
It gives me error
$ ./build.sh NDK_ROOT
: invalid optionopenblas.sh: line 2: set: -
set: usage: set [-abefhkmnptuvxBCHP] [-o option-name] [--] [arg ...]
Failed to build OpenBLAS
