### ISSUE TITLE
I want use the libcaffe.so and libcaffe_jni.so in Linux. What can I do to this?

### ISSUE THREAD

**Issue by Marryli** [sh1r0/caffe-android-lib#92]
I want use the libcaffe.so and libcaffe_jni.so in Linux. What can I do to this?If I only copy the file  to the Linux, it always makes errors.

**Comment by sh1r0** [comment]
The .so files built in this project are for android. Sorry that I could not get your idea.

**Comment by sh1r0** [comment]
Hi @Marryli, are #94 and #95 related to this one? If so, please reply in this issue and close the others, thanks. Also, I still cannot get your point. Are you trying to build java application based on caffe on linux and thus needs jni?

**Comment by Marryli** [comment]
Yes，that is my point.    Can you give me some ideas? Thanks.

**Comment by sh1r0** [comment]
I think you can take a look at https://github.com/bytedeco/javacpp-presets.
