### ISSUE TITLE
Failed to build openBLAS

### ISSUE THREAD

**Issue by DushyantMainwal** [sh1r0/caffe-android-lib#93]
I'm using cygwin in windows 7(64 bit) and it gives error="Failed to build openBLAS"
Here's what I did:

Dushyant@Dushyant-PC ~
$ cd D:

Dushyant@Dushyant-PC /cygdrive/d
$ cd softwares/sdk/caffe-android-lib

Dushyant@Dushyant-PC /cygdrive/d/softwares/sdk/caffe-android-lib
$ export NDK_ROOT=D:\Softwares\Sdk\androidsdk\ndk-bundle

Dushyant@Dushyant-PC /cygdrive/d/softwares/sdk/caffe-android-lib
$ export ANDROID_ABI="x86_64"

Dushyant@Dushyant-PC /cygdrive/d/softwares/sdk/caffe-android-lib
$ ./build.sh NDK_ROOT
: invalid optionopenblas.sh: line 2: set: -
set: usage: set [-abefhkmnptuvxBCHP] [-o option-name] [--] [arg ...]
Failed to build OpenBLAS

**Comment by sh1r0** [comment]
My guess is that `sh` on your platform does not support `set -e`. You could use `#!/usr/bin/env bash` rather than `#!/usr/bin/env sh` at the top of script.

**Comment by DushyantMainwal** [comment]
After changing it to bash in openBlas.sh gives the error..
$ ./build.sh NDK_ROOT
: invalid option 2: set: -
set: usage: set [-abefhkmnptuvxBCHP] [-o option-name] [--] [arg ...]
./build.sh: line 3: $'\r': command not found
./build.sh: line 35: syntax error: unexpected end of file

**Comment by sh1r0** [comment]
Sorry, I do not have such environment and it's not quite related to this project. As I said in https://github.com/sh1r0/caffe-android-lib/issues/91#issuecomment-270849334, it would be easy on linux or mac environment.
