### ISSUE TITLE
build failed with export ANDROID_ABI="armeabi-v7a-hard-softfp with NEON"

### ISSUE THREAD

**Issue by scottyyih** [sh1r0/caffe-android-lib#97]
How to solve this issue?

android-ndk-r13b/sources/cxx-stl/gnu-libstdc++/4.9/include/cstddef:44:28: fatal error: bits/c++config.h: No such file or directory
 #include <bits/c++config.h>
                            ^
compilation terminated.
CMakeFiles/boost_math.dir/build.make:62: recipe for target 'CMakeFiles/boost_math.dir/boost_1_56_0/libs/math/src/tr1/copysignf.cpp.o' failed

**Comment by sh1r0** [comment]
Please refer to https://github.com/sh1r0/caffe-android-lib/issues/57#issuecomment-255511524 and #68.

**Comment by scottyyih** [comment]
Hi sh1r0,
  Thank you very much.
