### ISSUE TITLE
libcaffe.so not found error when trying to run caffe on android device

### ISSUE THREAD

**Issue by raginisharma14** [sh1r0/caffe-android-lib#98]
I get Libcaffe.so not found error when I am trying to run caffe executable through AMD on mobile device. could you also let me know, what all files do I need to push on to the device through ADB to run one of the models successfully. 

I had copied only the caffe executable which is found inside the bin folder.

**Comment by sh1r0** [comment]
Hi @raginisharma14, you could refer to https://github.com/sh1r0/caffe-android-demo, which is the demo app for this lib. Besides, building caffe executable is not my main focus, and there are some known issues (e.g., https://github.com/sh1r0/caffe-android-lib/issues/89).
