### ISSUE TITLE
Error when config "armeabi-v7a-hard-softfp with NEON"

### ISSUE THREAD

**Issue by sfssqs** [sh1r0/caffe-android-lib#99]
Hi sh1r0, sorry to bother you, Error occurred when compile "armeabi-v7a-hard-softfp with NEON"

here is the log
---------------------------------------------------------------------------
Reversed (or previously applied) patch detected!  Skipping patch.
1 out of 1 hunk ignored
ERRORCould not find libsupc++.a for a chosen platform. Either your NDK is not supported or is broken.
-- Configuring done
-- Generating done
-- Build files have been written to: /home/caffe/caffe-android-lib/boost/build
Scanning dependencies of target boost_atomic
[  0%] Building CXX object CMakeFiles/boost_atomic.dir/boost_1_56_0/libs/atomic/src/lockpool.cpp.o
In file included from /home/caffe/caffe-android-lib/boost/boost_1_56_0/libs/atomic/src/lockpool.cpp:15:0:
/root/android-ndk-r12b/sources/cxx-stl/gnu-libstdc++/4.9/include/cstddef:44:28: fatal error: bits/c++config.h: No such file or directory
 #include <bits/c++config.h>

**Comment by sh1r0** [comment]
Please refer to  https://github.com/sh1r0/caffe-android-lib/issues/57#issuecomment-255511524 and #68, thanks.
